(()=>{
 const cleanText=t=>String(t||"").replace(/^[\s\.,!?؟،؛:。]+/u,"").trim();
 const report=(level,stage,message,meta)=>window.saeed?.reportDiagnostic?.(level,stage,message,meta);
 let mic=null,realtimeAssistant="",speechTimer=null,lastMicReport=0,micEnabled=false,voiceMuted=false,ttsReady=true,speechSuppressed=false,speechInterruptAt=0,speechInterruptFrames=0,micInterruptRms=0.09,micSpeechRms=0.02,lastRealtimeUserText="",lastRealtimeUserAt=0,realtimeBrainMode="auto",ttsProvider="local",sttProvider="whisper";
 const phonemeMap={a:"aa",e:"ee",i:"ee",o:"oh",u:"oo",y:"ee",b:"mbp",m:"mbp",p:"mbp",f:"fv",v:"fv",q:"oh",w:"oo",j:"ee"};
 function stopRealtimePlayback(){if(!mic)return;try{for(const src of mic.audioSources||[])src.stop()}catch{}if(mic.audioSources)mic.audioSources.clear();mic.nextPlayTime=0}
 function stopSpeaking(){stopRealtimePlayback();window.saeedCharacterRuntime?.controller?.handleEvent?.("speech-end");if("speechSynthesis"in window)window.speechSynthesis.cancel();if(speechTimer){clearInterval(speechTimer);speechTimer=null}["aa","ee","oo","oh","fv","mbp"].forEach(v=>window.saeedCharacterRuntime?.engine?.setCharacterViseme?.(v,0))}
function interruptAssistantSpeech(reason="user speech"){if(!speechSuppressed)return;speechInterruptAt=performance.now();speechInterruptFrames=0;speechSuppressed=false;stopSpeaking();try{window.saeed.voice.cancelRealtime?.()}catch{};report("INFO","TTS INTERRUPTED","Assistant speech stopped because user speech was detected",{reason})}
 function speakLocal(text){if(!text||!("speechSynthesis"in window)||voiceMuted)return;stopSpeaking();speechSuppressed=true;const clean=String(text).replace(/[ *_#]/g,""),u=new SpeechSynthesisUtterance(clean);u.lang="en-US";u.rate=.98;u.pitch=1;const chars=Array.from(clean);let pos=0;u.onstart=()=>{speechSuppressed=true;window.saeedCharacterRuntime?.controller?.handleEvent?.("speech-start");window.saeedCharacterRuntime?.controller?.play?.("talk");speechTimer=setInterval(()=>{window.saeedCharacterRuntime?.engine?.wakeRender?.(350);if(pos>=chars.length){clearInterval(speechTimer);speechTimer=null;return}const ch=chars[pos++],v=phonemeMap[ch.toLowerCase()]||"aa";["aa","ee","oo","oh","fv","mbp"].forEach(x=>window.saeedCharacterRuntime?.engine?.setCharacterViseme?.(x,0));if(!/\s/.test(ch))window.saeedCharacterRuntime?.engine?.setCharacterViseme?.(v,.72)},Math.max(45,70/u.rate))};u.onend=()=>{speechSuppressed=false;stopSpeaking();window.saeedCharacterRuntime?.controller?.play?.("idle")};u.onerror=e=>{const kind=String(e?.error||"").toLowerCase();speechSuppressed=false;if(kind==="interrupted"||kind==="canceled"||kind==="cancelled"){report("INFO","TTS LOCAL INTERRUPTED","Local TTS speech was cancelled",{reason:kind});}else report("ERROR","TTS LOCAL ERROR",e?.error||"Local TTS failed");stopSpeaking();window.saeedCharacterRuntime?.controller?.play?.("idle")};setTimeout(()=>{if(!voiceMuted&&ttsReady) window.speechSynthesis.speak(u)},20)}
 async function speakApi(text){
  if(!text||!ttsReady||voiceMuted)return;
  stopSpeaking();speechSuppressed=true;
  try{
   const r=await window.saeed.voice.ttsSpeak(text);
   if(!r?.ok){speechSuppressed=false;report("ERROR","TTS API",r?.error||"OpenAI TTS failed");window.saeedCharacterRuntime?.controller?.play?.("idle");return}
   if(!mic.playCtx)mic.playCtx=new AudioContext();
   await mic.playCtx.resume();
   const raw=Uint8Array.from(atob(r.base64),c=>c.charCodeAt(0));
   const buffer=await mic.playCtx.decodeAudioData(raw.buffer.slice(0));
   const src=mic.playCtx.createBufferSource();src.buffer=buffer;src.connect(mic.playCtx.destination);mic.audioSources.add(src);
   window.saeedCharacterRuntime?.controller?.handleEvent?.("speech-start");window.saeedCharacterRuntime?.controller?.play?.("talk");
   src.onended=()=>{mic.audioSources.delete(src);if(mic.audioSources.size===0){speechSuppressed=false;window.saeedCharacterRuntime?.controller?.handleEvent?.("speech-end");window.saeedCharacterRuntime?.controller?.play?.("idle")}};
   src.start();
  }catch(e){speechSuppressed=false;report("ERROR","TTS API PLAYBACK",e.message);window.saeedCharacterRuntime?.controller?.play?.("idle")}
 }
 function speakArabicPrayer(text){
  if(!text||voiceMuted||!("speechSynthesis"in window))return false;
  stopSpeaking();speechSuppressed=true;
  const u=new SpeechSynthesisUtterance(String(text));
  u.lang="ar-JO";u.rate=.88;u.pitch=1;
  u.onstart=()=>{speechSuppressed=true;window.saeedCharacterRuntime?.controller?.handleEvent?.("speech-start");window.saeedCharacterRuntime?.engine?.wakeRender?.(350)};
  u.onend=()=>{speechSuppressed=false;stopSpeaking();window.saeedCharacterRuntime?.controller?.handleEvent?.("speech-end")};
  u.onerror=()=>{speechSuppressed=false;stopSpeaking();window.saeedCharacterRuntime?.controller?.handleEvent?.("speech-end")};
  window.speechSynthesis.speak(u);return true;
 }
 window.saeedPrayerSpeak=speakArabicPrayer;
 window.saeedSpeakText=speak;
 function speak(text){
  if(!text||voiceMuted)return;
  window.saeedShowMessage?.(text);
  if(["openai","groq","elevenlabs"].includes(ttsProvider))return speakApi(text);
  return speakLocal(text);
 }
 class RealtimeMic{
  constructor(){this.stream=null;this.ctx=null;this.source=null;this.processor=null;this.monitorGain=null;this.active=false;this.generation=0;this.localSamples=[];this.localTranscribing=false;this.localSpeechActive=false;this.localLastSpeechAt=0;this.playCtx=null;this.nextPlayTime=0;this.audioSources=new Set()}
  async start(mode="on",sendAudio=true){
   const generation=++this.generation;if(mode==="off"){this.stop();return}if(this.active)return;
    if(!sendAudio&&realtimeBrainMode==="api"){
     const started=await window.saeed.voice.startRealtime?.();
     if(!started)throw new Error("Realtime API mode could not start. Check the Realtime API key and provider settings.");
     sendAudio=true;
    }
   if(!navigator.mediaDevices?.getUserMedia)throw new Error("Microphone capture is unavailable.");
   report("INFO","MIC START","Starting 3D-window microphone service",{mode});let stream;
   try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}})}
   catch(e){if(generation!==this.generation)return;report("ERROR","MIC OPEN ERROR",e?.message||"Microphone permission/device request failed",{name:e?.name||"UnknownError"});throw new Error("Microphone could not be opened: "+(e?.message||e?.name||"permission/device error"))}
   if(generation!==this.generation){try{stream.getTracks().forEach(t=>t.stop())}catch{};return}
   this.stream=stream;const tracks=stream.getAudioTracks();if(!tracks.length){this.stop();throw new Error("No audio input track was returned by Windows/Electron.")}
   tracks[0].onended=()=>{if(this.active){this.active=false;window.saeed?.reportMicLevel?.(0);report("ERROR","MIC ENDED","Windows/Electron microphone track ended unexpectedly")}};
   this.ctx=new AudioContext();try{await this.ctx.resume()}catch{}if(generation!==this.generation){this.stop();return}
   this.source=this.ctx.createMediaStreamSource(stream);this.processor=this.ctx.createScriptProcessor(4096,1,1);
   this.processor.onaudioprocess=e=>{if(!this.active||generation!==this.generation)return;const input=e.inputBuffer.getChannelData(0);let sum=0;for(let i=0;i<input.length;i++)sum+=input[i]*input[i];const rms=Math.sqrt(sum/Math.max(1,input.length)),level=Math.min(1,rms*6),now=performance.now();if(speechSuppressed){if(rms>=micInterruptRms&&now-speechInterruptAt>120){speechInterruptFrames++;if(speechInterruptFrames>=3)interruptAssistantSpeech("voice activity detected");}else{speechInterruptFrames=0;this.localSamples=[];this.localSpeechActive=false;return;}if(speechSuppressed){this.localSamples=[];this.localSpeechActive=false;return;}}if(now-lastMicReport>=120){lastMicReport=now;window.saeed?.reportMicLevel?.(level);report("INFO","MIC LEVEL","Microphone level "+Math.round(level*100)+"%",{level})};const ratio=24000/this.ctx.sampleRate,n=Math.max(1,Math.floor(input.length*ratio)),pcm=new Int16Array(n);for(let i=0;i<n;i++){const x=input[Math.min(input.length-1,Math.floor(i/ratio))]||0;pcm[i]=Math.max(-1,Math.min(1,x))*32767}if(sendAudio){let binary="";const bytes=new Uint8Array(pcm.buffer);for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));window.saeed.voice.sendRealtimeAudio(btoa(binary));}else{if(rms>=micSpeechRms){this.localSamples.push(pcm);this.localSpeechActive=true;this.localLastSpeechAt=now}else if(this.localSpeechActive&&now-this.localLastSpeechAt>700){this.localSpeechActive=false;this.flushLocalChunk()}}};
   this.source.connect(this.processor);this.monitorGain=this.ctx.createGain();this.monitorGain.gain.value=0;this.processor.connect(this.monitorGain);this.monitorGain.connect(this.ctx.destination);this.localSpeechActive=false;this.localLastSpeechAt=0;this.active=true;window.saeed?.reportMicLevel?.(0);report("INFO","MIC ACTIVE","3D-window microphone capture is active",{mode})
  }
  async flushLocalChunk(){if(!this.active||this.localTranscribing||!this.localSamples.length)return;const chunks=this.localSamples.splice(0);const total=chunks.reduce((n,a)=>n+a.length,0);if(total<2400)return;const pcm=new Int16Array(total);let offset=0;for(const chunk of chunks){pcm.set(chunk,offset);offset+=chunk.length}let binary="";const bytes=new Uint8Array(pcm.buffer);for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));this.localTranscribing=true;try{const encoded=btoa(binary);const result=sttProvider==="whisper"?await window.saeed.voice.transcribeLocalWav(encoded):await window.saeed.voice.sttTranscribe(encoded);if(!result?.ok&&result?.reason!=="stt-provider-local")throw new Error(result?.error||"STT provider failed");const text=String(result?.text||"").trim();if(text&&micEnabled){window.saeedShowTranscript?.(text);window.saeed.system.reportDiagnostic("INFO","STT RESULT",(sttProvider==="whisper"?"Offline Whisper":sttProvider.toUpperCase()+" API")+" transcript received",{provider:sttProvider,text});window.saeedCharacterRuntime?.controller?.semantic?.("think");const answer=await window.saeed.voice.voiceChat(text);if(answer){report("INFO","VOICE BRAIN ANSWER","Voice Brain returned an answer directly to voice",{text,answer:String(answer).slice(0,300)});window.saeedCharacterRuntime?.controller?.semantic?.("talk");window.saeedShowMessage?.(answer);await speak(answer);}else report("ERROR","VOICE BRAIN","Brain returned an empty answer for microphone input",{text})}else if(micEnabled)report("WARN","STT EMPTY RESULT","No words were recognized. Check microphone level or reduce Speech acceptance RMS.",{provider:sttProvider})}catch(e){report("ERROR",sttProvider==="whisper"?"LOCAL STT":"STT API",e.message)}finally{this.localTranscribing=false;if(this.active&&!this.localSpeechActive&&this.localSamples.reduce((n,a)=>n+a.length,0)>=12000)queueMicrotask(()=>{if(this.active&&!this.localTranscribing)void this.flushLocalChunk()})}}
 stop(){++this.generation;this.active=false;this.localSamples=[];this.localSpeechActive=false;this.localLastSpeechAt=0;try{for(const src of this.audioSources||[])src.stop()}catch{}try{this.audioSources?.clear()}catch{}try{this.processor?.disconnect()}catch{}try{this.monitorGain?.disconnect()}catch{}try{this.source?.disconnect()}catch{}try{this.stream?.getTracks().forEach(t=>t.stop())}catch{}try{this.ctx?.close()}catch{}try{this.playCtx?.close()}catch{}this.nextPlayTime=0;this.processor=null;this.monitorGain=null;this.source=null;this.stream=null;this.ctx=null;this.playCtx=null;this.audioSources=new Set();window.saeed?.reportMicLevel?.(0);report("INFO","MIC STOP","3D-window microphone capture stopped")}
 }
 mic=new RealtimeMic();
 let rmsSettingsTimer=null;
 async function refreshRmsSettings(){try{const s=await window.saeed.system.getSettings();micInterruptRms=Math.max(0.005,Math.min(0.5,Number(s?.micInterruptRms)||0.09));micSpeechRms=Math.max(0.005,Math.min(0.025,Number(s?.micSpeechRms)||0.02));realtimeBrainMode=["saeed","api","auto"].includes(s?.realtimeBrainMode)?s.realtimeBrainMode:"auto";ttsProvider=["openai","groq","elevenlabs"].includes(s?.ttsProvider)?s.ttsProvider:"local";voiceMuted=Boolean(s?.voiceMuted);sttProvider=["openai","groq","elevenlabs"].includes(s?.sttProvider)?s.sttProvider:"whisper"}catch{}}
 window.saeed.character.onCharacterBehavior?.(e=>{if(e?.type==="idle-thought"&&e.text)speak(e.text)});
 window.saeed.voice.onVoiceSpeak?.(text=>{if(text)speak(String(text));});
 window.saeed.voice.onVoiceMute(m=>{voiceMuted=Boolean(m);if(voiceMuted){stopSpeaking();report("INFO","VOICE MUTE","Saeed output is muted; microphone/input lifecycle remains unchanged")}});
  window.saeed.voice.onVoiceStop(()=>stopSpeaking());
  window.saeed.voice.onMicMode(async mode=>{const m=String(mode||"off");micEnabled=m==="on";try{if(m==="off"){mic.stop();if(rmsSettingsTimer){clearInterval(rmsSettingsTimer);rmsSettingsTimer=null}return}const cfg=await window.saeed.system.getSettings();micInterruptRms=Math.max(0.005,Math.min(0.5,Number(cfg?.micInterruptRms)||0.09));micSpeechRms=Math.max(0.005,Math.min(0.025,Number(cfg?.micSpeechRms)||0.02));realtimeBrainMode=["saeed","api","auto"].includes(cfg?.realtimeBrainMode)?cfg.realtimeBrainMode:"auto";ttsProvider=["openai","groq","elevenlabs"].includes(cfg?.ttsProvider)?cfg.ttsProvider:"local";sttProvider=["openai","groq","elevenlabs"].includes(cfg?.sttProvider)?cfg.sttProvider:"whisper";if(!rmsSettingsTimer)rmsSettingsTimer=setInterval(refreshRmsSettings,1000); await mic.start("on",false)}catch(e){report("ERROR","MIC START FAILURE",e.message,{mode:m});if(m==="on"){try{await window.saeed.voice.setMicMode("off")}catch{}}}});
 window.saeed.voice.onRealtimeState((state,message)=>{if(state==="connected")report("INFO","STT ACTIVE","Realtime speech-to-text connected");else if(state==="error")report("ERROR","REALTIME API ERROR",String(message||state));});
 window.saeed.voice.onRealtimeAudio(async b=>{try{if(!mic.playCtx)mic.playCtx=new AudioContext();try{await mic.playCtx.resume()}catch{}const raw=atob(b),pcm=new Int16Array(raw.length/2);for(let i=0;i<pcm.length;i++)pcm[i]=raw.charCodeAt(i*2)|(raw.charCodeAt(i*2+1)<<8);const buffer=mic.playCtx.createBuffer(1,pcm.length,24000),ch=buffer.getChannelData(0);for(let i=0;i<pcm.length;i++)ch[i]=pcm[i]/32768;const src=mic.playCtx.createBufferSource();src.buffer=buffer;src.connect(mic.playCtx.destination);const now=mic.playCtx.currentTime;mic.nextPlayTime=Math.max(now,Math.min(mic.nextPlayTime||now,now+.18));mic.audioSources.add(src);src.start(mic.nextPlayTime);mic.nextPlayTime+=buffer.duration;window.saeedCharacterRuntime?.controller?.handleEvent?.("speech-start");window.saeedCharacterRuntime?.controller?.play?.("talk");src.onended=()=>{mic.audioSources.delete(src);if(mic.audioSources.size===0&&mic.playCtx.currentTime>=mic.nextPlayTime-.02){window.saeedCharacterRuntime?.controller?.handleEvent?.("speech-end");window.saeedCharacterRuntime?.controller?.play?.("idle")}}}catch(e){report("ERROR","TTS AUDIO PLAYBACK",e.message)}});
 window.saeed.voice.onRealtimeAssistantDelta(t=>{realtimeAssistant+=String(t||"");window.saeedCharacterRuntime?.controller?.handleEvent?.("speech-start");window.saeedCharacterRuntime?.controller?.play?.("talk")});
 window.saeed.voice.onRealtimeAssistantFinal(t=>{if(t){realtimeAssistant="";window.saeedShowMessage?.(String(t));report("INFO","TTS TRANSCRIPT","Realtime assistant audio transcript received",{text:t})}});
 window.saeed.voice.onRealtimeUserFinal(async t=>{if(t){const clean=cleanText(t);if(!clean)return;const now=Date.now();if(clean===lastRealtimeUserText&&now-lastRealtimeUserAt<2500){report("INFO","STT DUPLICATE","Duplicate Realtime transcript ignored",{text:clean});return}lastRealtimeUserText=clean;lastRealtimeUserAt=now;window.saeedShowTranscript?.(clean);report("INFO","STT RECEIVE TEXT","Realtime speech received",{text:clean});if(!micEnabled||realtimeBrainMode==="api")return;try{window.saeedCharacterRuntime?.controller?.semantic?.("think");const answer=await window.saeed.voice.voiceChat(clean);if(answer){window.saeedCharacterRuntime?.controller?.semantic?.("talk");window.saeedShowMessage?.(answer);await speak(answer);}}catch(e){report("ERROR","BRAIN ROUTER","Realtime transcript could not reach the brain: "+e.message)}}});
 window.saeed.voice.onRealtimeError(e=>report("ERROR","REALTIME API ERROR",String(e)));
 window.saeed.voice.onLocalSttState((state,message)=>{report(state==="error"?"ERROR":"INFO","LOCAL STT STATE",String(message||state));if(state==="error"){window.saeedShowTranscript?.("Speech recognition error: "+String(message||state));window.saeedCharacterRuntime?.controller?.semantic?.("alert")}});
 window.saeed.chat.onEvent(e=>{if(e?.type==="thinking")window.saeedCharacterRuntime?.controller?.semantic?.("think");if(e?.type==="voice-answer")window.saeedCharacterRuntime?.controller?.semantic?.("nod");});window.saeed.system.onDiagnostic?.(e=>{if(e?.level==="ERROR"){const message="Error: "+String(e.stage||"Saeed")+" — "+String(e.message||"Unknown error");speak(message);window.saeedCharacterRuntime?.controller?.semantic?.("alert")}});
 window.addEventListener("load",()=>{report("INFO","VOICE READY","Voice control is user-activated; microphone starts only after an explicit Mic ON action",{micMode:"off"})});
})();

