function createWindowManager({BrowserWindow,path,windows,getWindow,setWindow,iconPath,diagnostic,startCpuMonitoring,stopCpuMonitoring,preloadPath}){
 async function showPerformance(){try{startCpuMonitoring();if(performanceWin&&!performanceWin.isDestroyed()){performanceWin.show();performanceWin.focus();return}performanceWin=new BrowserWindow({width:980,height:720,minWidth:760,minHeight:560,title:"Saeed Performance",show:false,resizable:true,skipTaskbar:false,icon:windowsIconPath(),webPreferences:{preload:path.join(__dirname,"..","preload.js"),contextIsolation:true,nodeIntegration:false,sandbox:false}});performanceWin.setIcon(windowsIconPath());performanceWin.on("closed",()=>{performanceWin=null;stopCpuMonitoring()});await performanceWin.loadFile(path.join(__dirname,"..","performance.html"));performanceWin.show();performanceWin.focus()}catch(e){diagnostic("ERROR","PERFORMANCE WINDOW",e.message)}}
 async function showSettings(){return showPerformance()}
 async function showLearning(){try{if(learningWin&&!learningWin.isDestroyed()){learningWin.show();learningWin.focus();return}learningWin=new BrowserWindow({width:1060,height:760,minWidth:760,minHeight:560,title:"Saeed Learning / Teach Mode",show:false,resizable:true,skipTaskbar:false,icon:windowsIconPath(),webPreferences:{preload:path.join(__dirname,"..","preload.js"),contextIsolation:true,nodeIntegration:false,sandbox:false}});learningWin.setIcon(windowsIconPath());learningWin.on("closed",()=>{learningWin=null});await learningWin.loadFile(path.join(__dirname,"..","learning","window.html"));learningWin.show();learningWin.focus()}catch(e){diagnostic("ERROR","LEARNING WINDOW",e.message)}}
 async function showAddons(){try{if(addonsWin&&!addonsWin.isDestroyed()){addonsWin.show();addonsWin.focus();addonsWin.webContents.send("addons:refresh");return}addonsWin=new BrowserWindow({width:1060,height:760,minWidth:760,minHeight:560,title:"Saeed Add-ons / Plug-ins",show:false,resizable:true,skipTaskbar:false,icon:windowsIconPath(),backgroundColor:"#f4f6fa",webPreferences:{preload:path.join(__dirname,"..","preload.js"),contextIsolation:true,nodeIntegration:false,sandbox:false}});addonsWin.setIcon(windowsIconPath());addonsWin.on("closed",()=>{addonsWin=null});addonsWin.webContents.once("did-finish-load",()=>{addonsWin?.show();addonsWin?.focus()});await addonsWin.loadFile(path.join(__dirname,"..","addons","window.html"))}catch(e){diagnostic("ERROR","ADDONS WINDOW",e.message)}}
 
 return {showPerformance,showSettings,showLearning,showAddons,showStatus};
}
module.exports={createWindowManager};
