"use strict";
const fs=require("node:fs"),path=require("node:path");
const {writeJsonAtomic}=require("./atomic-json-store");
const archive=require("../conversation/archive");
const SECRET_KEYS=new Set(["apiKey","sttApiKey","ttsApiKey","realtimeApiKey","fallbackApiKey"]);
const MAX_BACKUP_BYTES=15*1024*1024,MAX_FACTS=100,MAX_SETTING_KEYS=256;
function fail(message){throw new Error("Invalid Saeed backup: "+message)}
function safeSettings(input,allowedKeys){if(!input||typeof input!=="object"||Array.isArray(input))fail("settings must be an object");const allowed=new Set(Array.isArray(allowedKeys)?allowedKeys:[]);const out={};for(const [key,value] of Object.entries(input)){if(SECRET_KEYS.has(key)||["__proto__","prototype","constructor"].includes(key)||!allowed.has(key))continue;if(!/^[A-Za-z][A-Za-z0-9]{0,63}$/.test(key))continue;out[key]=value;}if(Object.keys(out).length>MAX_SETTING_KEYS)fail("too many settings");return out}
function normalizeFacts(value){if(!Array.isArray(value)||value.length>MAX_FACTS)fail("memory facts must be an array of at most "+MAX_FACTS+" items");return value.map((item,index)=>{if(!item||typeof item!=="object"||Array.isArray(item)||typeof item.text!=="string"||!item.text.trim()||item.text.length>2000)fail("memory fact "+index+" is invalid");return{key:String(item.key||item.text).trim().slice(0,180),text:item.text.trim(),createdAt:String(item.createdAt||new Date().toISOString()),updatedAt:String(item.updatedAt||new Date().toISOString())}})}
function validateBackup(input,allowedKeys=[]){let data=input;if(typeof input==="string"){if(Buffer.byteLength(input,"utf8")>MAX_BACKUP_BYTES)fail("file exceeds the 15 MB limit");try{data=JSON.parse(input)}catch{fail("file is not valid JSON")}}if(!data||typeof data!=="object"||Array.isArray(data))fail("root must be an object");if(data.format!=="saeed-ai-backup"||data.version!==1)fail("unsupported format or version");const settings=safeSettings(data.settings,allowedKeys);const conversations=archive.validateArchive(data.conversations);const facts=normalizeFacts(data.globalMemory?.facts||[]);const result={format:"saeed-ai-backup",version:1,createdAt:new Date(data.createdAt||Date.now()).toISOString(),settings,conversations,globalMemory:{schemaVersion:1,facts}};if(Buffer.byteLength(JSON.stringify(result),"utf8")>MAX_BACKUP_BYTES)fail("normalized backup exceeds the 15 MB limit");return result}
function createBackup({agent,userDataPath,allowedSettingKeys}={}){if(!agent)throw new Error("The Saeed agent is not available");const settings={...(agent.settings||{})};for(const key of SECRET_KEYS)delete settings[key];delete settings.micMode;const memory=require("./memory-service");const facts=memory.listFacts(userDataPath);const result={format:"saeed-ai-backup",version:1,createdAt:new Date().toISOString(),settings,conversations:archive.createArchive(agent.conversations||[]),globalMemory:{schemaVersion:1,facts}};return validateBackup(result,allowedSettingKeys||Object.keys(agent.settings||{}))}
function restoreBackup({backup,agent,userDataPath}={}){if(!agent)throw new Error("The Saeed agent is not available");const normalized=validateBackup(backup,Object.keys(agent.settings||{}));const memory=require("./memory-service");const oldSettings={...(agent.settings||{})},oldConversations=Array.isArray(agent.conversations)?agent.conversations.map(x=>({...x,messages:(x.messages||[]).map(m=>({...m}))})):[],oldConversationId=agent.currentConversationId,oldHistory=Array.isArray(agent.history)?agent.history.map(x=>({...x})):[],oldFacts=memory.listFacts(userDataPath);let oldLegacy=null;try{oldLegacy=fs.readFileSync(agent.memoryFile,"utf8")}catch{}
const safeKeys={...oldSettings,...normalized.settings};for(const key of SECRET_KEYS)if(Object.prototype.hasOwnProperty.call(oldSettings,key))safeKeys[key]=oldSettings[key];
try{agent.settings=safeKeys;agent.conversations=normalized.conversations.conversations.map(item=>({...item,messages:item.messages.map(m=>({...m}))}));agent.currentConversationId=agent.conversations[0]?.id||null;agent.history=agent.conversations[0]?.messages?.slice(-200)||[];if(!agent.saveConversations())throw new Error("Conversation archive could not be persisted");if(!agent.saveHistory())throw new Error("Current conversation could not be persisted");memory.writeFacts(userDataPath,normalized.globalMemory.facts);if(agent.memoryFile){const legacy=writeJsonAtomic(agent.memoryFile,{facts:normalized.globalMemory.facts});if(!legacy.ok)throw new Error("Legacy memory file could not be persisted: "+legacy.error)}agent.globalMemory={facts:memory.listFacts(userDataPath)};return{ok:true,conversations:agent.conversations.length,memoryFacts:agent.globalMemory.facts.length}}
catch(error){try{agent.settings=oldSettings}catch{}try{agent.conversations=oldConversations;agent.currentConversationId=oldConversationId;agent.history=oldHistory;agent.saveConversations();agent.saveHistory()}catch{}try{memory.writeFacts(userDataPath,oldFacts)}catch{}if(agent.memoryFile){try{if(oldLegacy!==null)fs.writeFileSync(agent.memoryFile,oldLegacy,"utf8");else fs.unlinkSync(agent.memoryFile)}catch{}}try{agent.globalMemory={facts:memory.listFacts(userDataPath)}}catch{}throw new Error("Backup restore failed; rollback was attempted: "+String(error?.message||error))}}
module.exports={MAX_BACKUP_BYTES,createBackup,validateBackup,restoreBackup};