const fs=require("fs"),path=require("path"),crypto=require("crypto");
const {writeJsonAtomic}=require("./atomic-json-store");
function root(userData){return path.join(userData,"addons","memory-stack")}
function ensure(userData){for(const d of ["knowledge","vectors","conversations"])fs.mkdirSync(path.join(root(userData),d),{recursive:true});return root(userData)}
function tokenize(text){return String(text||"").toLowerCase().normalize("NFKC").replace(/[^\p{L}\p{N}\s]/gu," ").split(/\s+/).filter(Boolean)}
function embed(text,dimensions=256){const v=new Array(dimensions).fill(0);for(const t of tokenize(text)){const h=crypto.createHash("sha256").update(t).digest();v[h.readUInt32BE(0)%dimensions]+=1;v[h.readUInt32BE(4)%dimensions]-=.5}const n=Math.sqrt(v.reduce((a,x)=>a+x*x,0))||1;return v.map(x=>x/n)}
function cosine(a,b){let dot=0,na=0,nb=0;for(let i=0;i<Math.max(a.length,b.length);i++){const x=Number(a[i]||0),y=Number(b[i]||0);dot+=x*y;na+=x*x;nb+=y*y}return na&&nb?dot/Math.sqrt(na*nb):0}
function vectorFile(u){return path.join(root(u),"vectors","index.json")}
function readVectors(u){ensure(u);let raw;try{raw=fs.readFileSync(vectorFile(u),"utf8")}catch(error){if(error?.code==="ENOENT")return{schemaVersion:1,items:[]};throw error}let data;try{data=JSON.parse(raw)}catch(error){throw new Error("Memory vector index is invalid JSON; refusing to overwrite it ("+error.message+")")}if(!data||typeof data!=="object"||data.schemaVersion!==1||!Array.isArray(data.items))throw new Error("Memory vector index has an unsupported or invalid structure; refusing to overwrite it");for(const [i,item] of data.items.entries()){if(!item||typeof item!=="object"||typeof item.id!=="string"||typeof item.text!=="string"||!Array.isArray(item.embedding)||item.embedding.some(n=>typeof n!=="number"||!Number.isFinite(n)))throw new Error("Memory vector index contains an invalid item at position "+i)}return data}
function writeVectors(u,d){ensure(u);const result=writeJsonAtomic(vectorFile(u),d);if(!result.ok)throw new Error("Memory vector index persistence failed: "+result.error);return true}
function add(u,text,meta={}){const value=String(text||"").trim();if(!value)throw new Error("Memory text is empty");const d=readVectors(u),id=crypto.createHash("sha256").update(value+JSON.stringify(meta)).digest("hex").slice(0,24);d.items=d.items.filter(x=>x.id!==id);d.items.push({id,text:value,metadata:meta,embedding:embed(value),createdAt:new Date().toISOString()});writeVectors(u,d);return d.items.at(-1)}
function search(u,q,limit=5){const d=readVectors(u),v=embed(q);return d.items.map(x=>({...x,score:cosine(v,x.embedding)})).sort((a,b)=>b.score-a.score).slice(0,Math.max(1,Number(limit)||5))}
function rememberConversation(u,id,role,text){ensure(u);const f=path.join(root(u),"conversations",String(id).replace(/[^a-z0-9._-]/gi,"_")+".jsonl");fs.appendFileSync(f,JSON.stringify({role,text,at:new Date().toISOString()})+"\n","utf8");return true}
function addKnowledge(u,text,metadata={}){const value=String(text||"").trim();if(!value)throw new Error("Knowledge text is empty");const f=path.join(root(u),"knowledge",crypto.createHash("sha256").update(value).digest("hex").slice(0,24)+".json");const result=writeJsonAtomic(f,{text:value,metadata,updatedAt:new Date().toISOString()});if(!result.ok)throw new Error("Knowledge persistence failed: "+result.error);return add(u,value,{...metadata,type:"knowledge"})}
function rag(u,q,limit=5){return search(u,q,limit).filter(x=>x.score>0)}
function factsFile(u){return path.join(root(u),"knowledge","facts.json")}
function readFacts(u){ensure(u);let raw;try{raw=fs.readFileSync(factsFile(u),"utf8")}catch(error){if(error?.code==="ENOENT")return[];throw error}let data;try{data=JSON.parse(raw)}catch(error){throw new Error("Memory facts file is invalid JSON; refusing to overwrite it ("+error.message+")")}if(!data||typeof data!=="object"||data.schemaVersion!==1||!Array.isArray(data.facts)||data.facts.some(x=>!x||typeof x!=="object"||typeof x.text!=="string"))throw new Error("Memory facts file has an unsupported or invalid structure; refusing to overwrite it");return data.facts}
function writeFacts(u,facts){ensure(u);const result=writeJsonAtomic(factsFile(u),{schemaVersion:1,facts});if(!result.ok)throw new Error("Memory facts persistence failed: "+result.error);return true}
function migrateLegacyFacts(u,legacyFile){const facts=readFacts(u);if(facts.length)return facts;try{if(!legacyFile||!fs.existsSync(legacyFile))return facts;const legacy=JSON.parse(fs.readFileSync(legacyFile,"utf8"));const incoming=Array.isArray(legacy?.facts)?legacy.facts:[];if(!incoming.length)return facts;const migrated=incoming.map(x=>({key:String(x.key||x.text||"").toLowerCase().replace(/\s+/g," ").slice(0,180),text:String(x.text||"").trim(),createdAt:x.createdAt||new Date().toISOString(),updatedAt:x.updatedAt||new Date().toISOString()})).filter(x=>x.text);writeFacts(u,migrated);return migrated}catch{return facts}}
function addFact(u,text){const value=String(text||"").trim();if(!value)return null;const facts=readFacts(u),key=value.toLowerCase().replace(/\s+/g," ").slice(0,180),now=new Date().toISOString(),existing=facts.find(x=>x.key===key);if(existing){existing.text=value;existing.updatedAt=now}else facts.push({key,text:value,createdAt:now,updatedAt:now});writeFacts(u,facts.slice(-100));const indexed=add(u,value,{type:"fact",key});const vectors=readVectors(u),before=vectors.items.length;vectors.items=vectors.items.filter(x=>x.id===indexed.id||x.metadata?.type!=="fact"||x.metadata?.key!==key);if(vectors.items.length!==before)writeVectors(u,vectors);return facts.find(x=>x.key===key)}
function listFacts(u){return readFacts(u)}
function forget(u,q){
 const query=String(q||"").trim().toLowerCase();
 if(!query)return{removed:0,removedVectors:0,removedFacts:0,removedKnowledge:0};
 const d=readVectors(u),before=d.items.length,removedItems=d.items.filter(x=>String(x.id)===query||String(x.text||"").toLowerCase().includes(query)),removedTexts=new Set(removedItems.map(x=>String(x.text||"").toLowerCase()).filter(Boolean));
 d.items=d.items.filter(x=>!removedItems.includes(x));
 if(d.items.length!==before)writeVectors(u,d);
 const facts=readFacts(u),kept=facts.filter(x=>String(x.key||"").toLowerCase()!==query&&!removedTexts.has(String(x.text||"").toLowerCase())&&String(x.text||"").toLowerCase().includes(query)===false),removedFacts=facts.length-kept.length;
 if(removedFacts)writeFacts(u,kept);
 let removedKnowledge=0;
 try{const dir=path.join(root(u),"knowledge");for(const name of fs.readdirSync(dir)){if(name==="facts.json"||!name.endsWith(".json"))continue;const file=path.join(dir,name);try{const item=JSON.parse(fs.readFileSync(file,"utf8")),textValue=String(item.text||item.title||""),normalized=textValue.toLowerCase();if(String(item.id||"").toLowerCase()===query||removedTexts.has(normalized)||normalized.includes(query)){fs.unlinkSync(file);removedKnowledge++}}catch{}}}catch{}
 return{removed:before-d.items.length+removedFacts+removedKnowledge,removedVectors:before-d.items.length,removedFacts,removedKnowledge};
}
module.exports={root,ensure,embed,cosine,add,search,rememberConversation,addKnowledge,rag,forget,factsFile,readFacts,writeFacts,migrateLegacyFacts,addFact,listFacts};
