function createCharacterHost({app,ipcMain,BrowserWindow,dialog,path,fs,screen,diagnostic,windowsIconPath,getCharacterWindow,getRestPoseEditorWindow,setCharacterWindow,getAgent,characterStore,contextMenu}){
 ipcMain?.on("character:renderer-ready",event=>{if(!pendingCharacterData)return;try{event.sender.send("character:selected",pendingCharacterData.data,pendingCharacterData.generation)}catch(error){diagnostic("ERROR","GLB DELIVERY",error?.message||String(error))}});
 const {persistSelectedCharacter,readPersistedCharacter,readCharacter3DSettings,writeCharacter3DSettings,applyCharacter3DWindowSettings,captureCharacter3DWindowSettings,character3DSettingsFile}=characterStore;let characterLoadGeneration=0,pendingCharacterData=null,saveMoveTimer=null;
 function displayForWindow(){const target=getCharacterWindow();if(!target)return screen.getPrimaryDisplay();const [x,y]=target.getPosition(),[w,h]=target.getSize();return screen.getDisplayMatching({x,y,width:w,height:h})||screen.getDisplayNearestPoint({x:x+w/2,y:y+h/2})||screen.getPrimaryDisplay()}
 function fitCharacterToDisplay(display=displayForWindow(),{bottomRight=false}={}){const target=getCharacterWindow();if(!target)return;const a=display.workArea,[w,h]=target.getSize(),m=18,[x0,y0]=target.getPosition();const x=bottomRight?a.x+Math.max(0,a.width-w-m):Math.max(a.x,Math.min(x0,a.x+Math.max(0,a.width-w))),y=bottomRight?a.y+Math.max(0,a.height-h-m):Math.max(a.y,Math.min(y0,a.y+Math.max(0,a.height-h)));target.setPosition(Math.round(x),Math.round(y),false)}
 function sendCharacterData(data){const generation=++characterLoadGeneration;pendingCharacterData={data,generation};return sendPendingCharacterDataToCharacterWindow()} function sendPendingCharacterDataToCharacterWindow(target=getCharacterWindow()){if(!target||target.isDestroyed()||!pendingCharacterData)return false;try{target.webContents.send("character:selected",pendingCharacterData.data,pendingCharacterData.generation);return true}catch(error){diagnostic("ERROR","GLB DELIVERY",error?.message||String(error));return false}}
 function chooseCharacter(){return dialog.showOpenDialog(getCharacterWindow(),{title:"Choose Saeed Character",filters:[{name:"GLB 3D Character",extensions:["glb"]}],properties:["openFile"]}).then(r=>{if(r.canceled||!r.filePaths[0])return;const file=r.filePaths[0];try{const data=fs.readFileSync(file),persisted=persistSelectedCharacter(data);sendCharacterData(new Uint8Array(data));const agent=getAgent();if(agent){agent.settings={...agent.settings,selectedCharacterName:path.basename(file)};agent.persistSettings()}diagnostic("INFO","GLB SELECTED","Character GLB selected and saved",{name:path.basename(file),size:data.length,persistedPath:persisted})}catch(e){diagnostic("ERROR","GLB SELECTED",e.message)}})}
 async function replaceCharacterForCi(file){const target=getCharacterWindow();if(!target||target.isDestroyed())return{ok:false,error:"Character window is unavailable"};try{const source=String(file||"");if(!source||!fs.existsSync(source))return{ok:false,error:"GLB test file is missing"};const data=fs.readFileSync(source);if(data.length<20)return{ok:false,error:"GLB test file is too small"};const persisted=persistSelectedCharacter(data);sendCharacterData(new Uint8Array(data));const agent=getAgent();if(agent){agent.settings={...agent.settings,selectedCharacterName:path.basename(source)};agent.persistSettings()}diagnostic("INFO","GLB CI REPLACEMENT","CI replaced character GLB",{name:path.basename(source),size:data.length,persistedPath:persisted});const deadline=Date.now()+15000;let loaded=false;while(Date.now()<deadline){try{const status=await target.webContents.executeJavaScript("(()=>{const b=window.saeed3DBootstrap||{};const e=window.saeedCharacterRuntime?.engine?.get3DStatus?.();return {moduleLoaded:b.moduleLoaded!==false,error:b.error||null,rendered:e?.components?.sceneContent?.state===\"rendered\"}})()",true);if(status?.error)throw new Error(status.error);if(status?.moduleLoaded&&status?.rendered){loaded=true;break}}catch(error){if(String(error?.message||error).includes("3D"))throw error}await new Promise(resolve=>setTimeout(resolve,250))}if(!loaded)return{ok:false,error:"GLB replacement was sent but the 3D character did not reach rendered state within 15 seconds",name:path.basename(source),size:data.length,persistedPath:persisted};return{ok:true,name:path.basename(source),size:data.length,persistedPath:persisted}}catch(e){diagnostic("ERROR","GLB CI REPLACEMENT",e.message);return{ok:false,error:e.message}}}
 function setSaeedSize(size){const m={small:[300,360],medium:[430,520],large:[560,660]},key=Object.prototype.hasOwnProperty.call(m,size)?size:"medium",v=m[key],target=getCharacterWindow();if(target&&!target.isDestroyed()){const d=displayForWindow(),a=d.workArea,m=18,[ox,oy]=target.getPosition(),[ow,oh]=target.getSize(),right=ox+ow,bottom=oy+oh,x=Math.max(a.x,Math.min(right-v[0],a.x+a.width-v[0]-m)),y=Math.max(a.y,Math.min(bottom-v[1],a.y+a.height-v[1]-m));target.setMinimumSize(300,360);target.setMaximumSize(900,900);target.setResizable(true);target.setSize(v[0],v[1],false);target.setPosition(Math.round(x),Math.round(y),false);target.webContents.send("character:size",key)}const agent=getAgent();if(agent){agent.settings={...agent.settings,characterSize:key};agent.persistSettings()}}
 async function showCharacter(){try{let target=getCharacterWindow();if(!target||target.isDestroyed())await createCharacterWindow();target=getCharacterWindow();if(!target||target.isDestroyed())return;target.webContents.setBackgroundThrottling(false);target.webContents.send("character:visibility","visible");target.show();target.focus()}catch(e){diagnostic("ERROR","3D WINDOW",e.message)}}
 function hideCharacter(){const target=getCharacterWindow();if(!target||target.isDestroyed())return;try{captureCharacter3DWindowSettings()}catch{}try{target.webContents.send("character:visibility","hidden")}catch{}try{target.destroy()}catch{}setCharacterWindow(null);diagnostic("INFO","3D WINDOW","Saeed hidden: 3D renderer window destroyed; tray remains active")}
 async function createCharacterWindow(){let target=getCharacterWindow();if(target&&!target.isDestroyed())return target;target=new BrowserWindow({name:"saeed-character",width:430,height:520,minWidth:300,minHeight:360,frame:false,transparent:true,alwaysOnTop:true,show:false,hasShadow:false,resizable:true,skipTaskbar:false,icon:windowsIconPath(),webPreferences:{preload:path.join(__dirname,"..","..","preload.js"),contextIsolation:true,nodeIntegration:false,sandbox:false,backgroundThrottling:false,autoplayPolicy:"no-user-gesture-required"}});target.setIcon(windowsIconPath());if(process.platform==="win32")target.setAppDetails({appId:"ai.saeed.desktop",appIconPath:windowsIconPath(),appIconIndex:0,relaunchCommand:process.execPath,relaunchDisplayName:"Saeed AI Character"});target.on("move",()=>{clearTimeout(saveMoveTimer);saveMoveTimer=setTimeout(()=>{try{captureCharacter3DWindowSettings()}catch{}},250)});target.on("closed",()=>{clearTimeout(saveMoveTimer);try{captureCharacter3DWindowSettings()}catch{};setCharacterWindow(null)});target.webContents.on("context-menu",()=>contextMenu?.());setCharacterWindow(target);await target.loadFile(path.join(__dirname,"..","..","renderer","character.html"));applyCharacter3DWindowSettings();try{const bundled=path.join(__dirname,"..","..","..","assets","Saeed_AI-3D.glb");if(!fs.existsSync(bundled))throw new Error("Authoritative Saeed GLB is missing: "+bundled);const data=fs.readFileSync(bundled);if(data.length<20)throw new Error("Authoritative Saeed GLB is invalid or empty: "+bundled);pendingCharacterData={data:new Uint8Array(data),generation:++characterLoadGeneration};sendPendingCharacterData();setTimeout(()=>{const w=getCharacterWindow();if(w&&!w.isDestroyed()&&pendingCharacterData){try{w.webContents.send("character:selected",pendingCharacterData.data,pendingCharacterData.generation)}catch(e){diagnostic("ERROR","GLB STARTUP DELIVERY",e?.message||String(e))}}},0);diagnostic("INFO","GLB STARTUP","Loaded authoritative bundled Saeed GLB",{path:bundled,size:data.length})}catch(e){diagnostic("ERROR","GLB STARTUP",e.message)}const positionState=readCharacter3DSettings();if(positionState.window.positionInitialized&&Number.isFinite(Number(positionState.window.x))&&Number.isFinite(Number(positionState.window.y))){applyCharacter3DWindowSettings()}else{fitCharacterToDisplay(screen.getPrimaryDisplay(),{bottomRight:true});const [x,y]=target.getPosition();writeCharacter3DSettings({...positionState,window:{...positionState.window,x,y,positionInitialized:true}})}target.show();return target}
 async function command(command={}){
  let win=getCharacterWindow();
  if(!win||win.isDestroyed()){
   try{win=await createCharacterWindow()}catch(error){return{ok:false,error:error?.message||String(error)}}
   win=getCharacterWindow();
  }
  if(!win||win.isDestroyed())return{ok:false,error:"Character window could not be created"};
  if(!ipcMain)return{ok:false,error:"Character command IPC is unavailable"};
  try{win.webContents.setBackgroundThrottling(false)}catch{}
  if(win.webContents.isLoadingMainFrame?.()){
   try{await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{cleanup();reject(new Error("Character renderer did not finish loading"))},15000);const cleanup=()=>{clearTimeout(timer);win.webContents.removeListener("did-finish-load",ready);win.webContents.removeListener("did-fail-load",failed)};const ready=()=>{cleanup();resolve()};const failed=(_,code,description)=>{cleanup();reject(new Error("Character renderer load failed ("+code+"): "+description))};win.webContents.once("did-finish-load",ready);win.webContents.once("did-fail-load",failed)})}catch(error){return{ok:false,error:error?.message||String(error)}}
  }
  const requestId="character-command-"+Date.now()+"-"+(++characterLoadGeneration);
  return await new Promise(resolve=>{
   let settled=false;
   const finish=result=>{if(settled)return;settled=true;clearTimeout(timeout);ipcMain.removeListener("character:command-result",onResult);resolve(result)};
   const onResult=(_,id,result)=>{if(id===requestId)finish(result)};
   const timeout=setTimeout(()=>finish({ok:false,error:"Character command timed out"}),30000);
   ipcMain.on("character:command-result",onResult);
   try{win.webContents.send("character:command",requestId,command)}catch(error){finish({ok:false,error:error?.message||String(error)})}
  });
 }
 function sendPendingCharacterData(){
  const editor=getRestPoseEditorWindow?.();
  if(!editor||editor.isDestroyed()||!pendingCharacterData)return false;
  editor.webContents.send("character:selected",pendingCharacterData.data,pendingCharacterData.generation);
  return true;
 }
 function characterSizeMenu(){return[{label:"Small",click:()=>setSaeedSize("small")},{label:"Medium",click:()=>setSaeedSize("medium")},{label:"Large",click:()=>setSaeedSize("large")}]}
 return{displayForWindow,fitCharacterToDisplay,sendCharacterData,sendPendingCharacterData,getPendingCharacter:()=>pendingCharacterData?{data:pendingCharacterData.data,generation:pendingCharacterData.generation}:null,replaceCharacterForCi,chooseCharacter,setSaeedSize,showCharacter,hideCharacter,createCharacterWindow,command,characterSizeMenu,captureCharacter3DWindowSettings,readCharacter3DSettings,writeCharacter3DSettings,character3DSettingsFile};
}
module.exports={createCharacterHost};