function createCharacterHost({app,BrowserWindow,dialog,path,fs,screen,diagnostic,windowsIconPath,getCharacterWindow,setCharacterWindow,getAgent,characterStore,showChat,permissionPolicy,confirmPermission}){
 const {persistSelectedCharacter,readPersistedCharacter,readCharacter3DSettings,writeCharacter3DSettings,applyCharacter3DWindowSettings,captureCharacter3DWindowSettings,character3DSettingsFile}=characterStore;
 let characterLoadGeneration=0,pendingCharacterData=null;
 function displayForWindow(){const target=getCharacterWindow();if(!target)return screen.getPrimaryDisplay();const [x,y]=target.getPosition(),[w,h]=target.getSize();return screen.getDisplayMatching({x,y,width:w,height:h})||screen.getDisplayNearestPoint({x:x+w/2,y:y+h/2})||screen.getPrimaryDisplay()}
 function fitCharacterToDisplay(display=displayForWindow(),{bottomRight=false}={}){const target=getCharacterWindow();if(!target)return;const area=display.workArea;const [w,h]=target.getSize(),margin=18,[x0,y0]=target.getPosition();const x=bottomRight?area.x+Math.max(0,area.width-w-margin):Math.max(area.x,Math.min(x0,area.x+Math.max(0,area.width-w)));const y=bottomRight?area.y+Math.max(0,area.height-h-margin):Math.max(area.y,Math.min(y0,area.y+Math.max(0,area.height-h)));target.setPosition(Math.round(x),Math.round(y),false)}
 function sendCharacterData(data){const generation=++characterLoadGeneration;const target=getCharacterWindow();pendingCharacterData={data,generation};if(!target||target.isDestroyed())return false;target.webContents.send("character:selected",data,generation);return true}
 function chooseCharacter(){return dialog.showOpenDialog(getCharacterWindow(),{title:"Choose Saeed Character",filters:[{name:"GLB 3D Character",extensions:["glb"]}],properties:["openFile"]}).then(r=>{if(r.canceled||!r.filePaths[0])return;const file=r.filePaths[0];try{const data=fs.readFileSync(file),persisted=persistSelectedCharacter(data);sendCharacterData(new Uint8Array(data));const agent=getAgent();if(agent){agent.settings={...agent.settings,selectedCharacterName:path.basename(file)};agent.persistSettings()}diagnostic("INFO","GLB SELECTED","Character GLB selected and saved for next launch",{name:path.basename(file),size:data.length,persistedPath:persisted})}catch(e){diagnostic("ERROR","GLB SELECTED",e.message)}})}
 function setSaeedSize(size){const m={small:[300,360],medium:[430,520],large:[560,660]},key=Object.prototype.hasOwnProperty.call(m,size)?size:"medium",v=m[key],target=getCharacterWindow();if(target&&!target.isDestroyed()){const d=displayForWindow(),a=d.workArea,margin=18,[oldX,oldY]=target.getPosition(),[oldW,oldH]=target.getSize(),oldRight=oldX+oldW,oldBottom=oldY+oldH,x=Math.max(a.x,Math.min(oldRight-v[0],a.x+a.width-v[0]-margin)),y=Math.max(a.y,Math.min(oldBottom-v[1],a.y+a.height-v[1]-margin));target.setMinimumSize(300,360);target.setMaximumSize(900,900);target.setResizable(true);target.setSize(v[0],v[1],false);target.setPosition(Math.round(x),Math.round(y),false);target.webContents.send("character:size",key)}const agent=getAgent();if(agent){agent.settings={...agent.settings,characterSize:key};agent.persistSettings()}}
 async function showCharacter(){try{let target=getCharacterWindow();if(!target||target.isDestroyed())await createCharacterWindow();target=getCharacterWindow();if(!target||target.isDestroyed())return;target.webContents.setBackgroundThrottling(false);target.webContents.send("character:visibility","visible");target.show();target.focus()}catch(e){diagnostic("ERROR","3D WINDOW",e.message)}}
 function hideCharacter(){const target=getCharacterWindow();if(!target||target.isDestroyed())return;try{captureCharacter3DWindowSettings()}catch{}try{target.webContents.send("character:visibility","hidden");target.webContents.setBackgroundThrottling(true)}catch{}try{target.hide()}catch{}}
 async function createCharacterWindow(){let target=getCharacterWindow();if(target&&!target.isDestroyed())return target;target=new BrowserWindow({name:"saeed-character",width:430,height:520,minWidth:300,minHeight:360,frame:false,transparent:true,alwaysOnTop:true,show:false,hasShadow:false,resizable:true,skipTaskbar:false,icon:windowsIconPath(),webPreferences:{preload:path.join(__dirname,"..","preload.js"),contextIsolation:true,nodeIntegration:false,sandbox:false}});target.setIcon(windowsIconPath());if(process.platform==="win32")target.setAppDetails({appId:"ai.saeed.desktop",appIconPath:windowsIconPath(),appIconIndex:0,relaunchCommand:process.execPath,relaunchDisplayName:"Saeed AI Character"});target.on("closed",()=>{try{captureCharacter3DWindowSettings()}catch{};setCharacterWindow(null)});target.on("close",()=>{if(!app.isQuitting)diagnostic("INFO","WINDOW","Saeed character window closed")});target.webContents.on("context-menu",()=>{});setCharacterWindow(target);await target.loadFile(path.join(__dirname,"..","character.html"));applyCharacter3DWindowSettings();try{const saved=readPersistedCharacter(),bundled=path.join(__dirname,"..","..","assets","Saeed_Test-3D.glb"),source=saved||((fs.existsSync(bundled))?{data:new Uint8Array(fs.readFileSync(bundled)),path:bundled,size:fs.statSync(bundled).size}:null);if(source){pendingCharacterData={data:source.data,generation:++characterLoadGeneration};setTimeout(()=>{const w=getCharacterWindow();if(w&&!w.isDestroyed()&&pendingCharacterData)w.webContents.send("character:selected",pendingCharacterData.data,pendingCharacterData.generation)},0);diagnostic("INFO",saved?"GLB RESTORE":"GLB DEFAULT",saved?"Previously selected character restored":"Bundled Saeed_Test-3D.glb loaded as the default character",{size:source.size,path:source.path})}else diagnostic("ERROR","GLB DEFAULT","No default or persisted Saeed GLB is available")}catch(e){diagnostic("ERROR","GLB STARTUP",e.message)}if(!Number.isFinite(Number(readCharacter3DSettings().window.x))||!Number.isFinite(Number(readCharacter3DSettings().window.y)))fitCharacterToDisplay(screen.getPrimaryDisplay(),{bottomRight:true});target.show();return target}
 function characterSizeMenu(){return[{label:"Small",click:()=>setSaeedSize("small")},{label:"Medium",click:()=>setSaeedSize("medium")},{label:"Large",click:()=>setSaeedSize("large")}]}
 return {displayForWindow,fitCharacterToDisplay,sendCharacterData,chooseCharacter,setSaeedSize,showCharacter,hideCharacter,createCharacterWindow,characterSizeMenu,captureCharacter3DWindowSettings,readCharacter3DSettings,writeCharacter3DSettings,character3DSettingsFile};
}
module.exports={createCharacterHost};
