function createCharacterStore({app,path,fs,screen,getCharacterWindow,fitCharacterToDisplay,diagnostic}){
 const persistedCharacterFile=()=>path.join(app.getPath("userData"),"characters","selected.glb");
 const character3DSettingsFile=()=>path.join(app.getPath("userData"),"characters","3d-settings.json");
 const DEFAULT_CHARACTER_3D={window:{width:430,height:520,x:null,y:null},camera:{zoom:1,fov:30,rotationX:0,rotationY:0,rotationZ:0,offsetX:0,offsetY:0,offsetZ:0},character:{scale:1,positionX:0,positionY:0,positionZ:0,rotationY:0},canvas:{padding:0}};
 function readCharacter3DSettings(){try{const f=character3DSettingsFile();if(!fs.existsSync(f))return JSON.parse(JSON.stringify(DEFAULT_CHARACTER_3D));const raw=JSON.parse(fs.readFileSync(f,"utf8"));return{...DEFAULT_CHARACTER_3D,...raw,window:{...DEFAULT_CHARACTER_3D.window,...raw.window},camera:{...DEFAULT_CHARACTER_3D.camera,...raw.camera},character:{...DEFAULT_CHARACTER_3D.character,...raw.character},canvas:{...DEFAULT_CHARACTER_3D.canvas,...raw.canvas}}}catch(e){diagnostic("ERROR","3D SETTINGS LOAD",e.message);return JSON.parse(JSON.stringify(DEFAULT_CHARACTER_3D))}}
 function writeCharacter3DSettings(value){try{const merged={...DEFAULT_CHARACTER_3D,...value,window:{...DEFAULT_CHARACTER_3D.window,...value?.window},camera:{...DEFAULT_CHARACTER_3D.camera,...value?.camera},character:{...DEFAULT_CHARACTER_3D.character,...value?.character},canvas:{...DEFAULT_CHARACTER_3D.canvas,...value?.canvas}};const f=character3DSettingsFile();fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(merged,null,2),"utf8");return merged}catch(e){diagnostic("ERROR","3D SETTINGS SAVE",e.message);throw e}}
 function applyCharacter3DWindowSettings(){const characterWin=getCharacterWindow();if(!characterWin||characterWin.isDestroyed())return;const s=readCharacter3DSettings(),w=Math.max(300,Math.min(1400,Math.round(Number(s.window.width)||430))),h=Math.max(360,Math.min(1400,Math.round(Number(s.window.height)||520)));characterWin.setMinimumSize(300,360);characterWin.setMaximumSize(1400,1400);characterWin.setResizable(true);characterWin.setSize(w,h,false);if(Number.isFinite(Number(s.window.x))&&Number.isFinite(Number(s.window.y))){const d=screen.getDisplayNearestPoint({x:Number(s.window.x)+w/2,y:Number(s.window.y)+h/2})||screen.getPrimaryDisplay();const a=d.workArea;const x=Math.max(a.x,Math.min(Math.round(Number(s.window.x)),a.x+a.width-w));const y=Math.max(a.y,Math.min(Math.round(Number(s.window.y)),a.y+a.height-h));characterWin.setPosition(x,y,false)}else fitCharacterToDisplay(screen.getPrimaryDisplay(),{bottomRight:true});characterWin.webContents.send("character:3d-settings",s)}
 function captureCharacter3DWindowSettings(){const characterWin=getCharacterWindow();if(!characterWin||characterWin.isDestroyed())return readCharacter3DSettings();const [x,y]=characterWin.getPosition(),[width,height]=characterWin.getSize();const s=readCharacter3DSettings();s.window={...s.window,x,y,width,height};return writeCharacter3DSettings(s)}
 function persistSelectedCharacter(data){try{const file=persistedCharacterFile();fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,Buffer.from(data));return file}catch(e){diagnostic("ERROR","GLB PERSIST",e.message);return null}}
 function readPersistedCharacter(){try{const file=persistedCharacterFile();if(!fs.existsSync(file))return null;const data=fs.readFileSync(file);return{data:new Uint8Array(data),path:file,size:data.length}}catch(e){diagnostic("ERROR","GLB RESTORE",e.message);return null}}
 return {persistedCharacterFile,character3DSettingsFile,readCharacter3DSettings,writeCharacter3DSettings,applyCharacter3DWindowSettings,captureCharacter3DWindowSettings,persistSelectedCharacter,readPersistedCharacter};
}
module.exports={createCharacterStore};
