const $=id=>document.getElementById(id),list=$("list"),message=$("message");let selectedSkill=null,recording=false;
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function render(items){list.innerHTML=items.map(s=>'<article class="card" data-skill="'+esc(s.id)+'"><div class="name">'+esc(s.name)+'</div><div class="meta">'+esc(s.id)+' · v'+esc(s.version)+' · '+(s.enabled!==false?"Enabled":"Disabled")+'</div><div class="phrases">'+(s.trigger?.phrases||[]).map(esc).join(" · ")+'</div>'+(s.steps||[]).map((x,i)=>'<div class="step">'+(i+1)+'. '+esc(x.tool)+' '+esc(JSON.stringify(x.args||{}))+'</div>').join("")+'<div class="actions"><button data-select="'+esc(s.id)+'">Edit</button><button data-run="'+esc(s.id)+'">Run</button><button class="toggle" data-toggle="'+esc(s.id)+'">'+(s.enabled!==false?"Disable":"Enable")+'</button><button class="danger" data-remove="'+esc(s.id)+'">Delete</button></div></article>').join("");
list.querySelectorAll("[data-select]").forEach(b=>b.onclick=async()=>{selectedSkill=b.dataset.select;const s=await window.saeed.learning.get(selectedSkill);$("name").value=s.name;$("phrases").value=s.trigger.phrases.join(" | ");$("steps").value=JSON.stringify(s.steps,null,2)});
list.querySelectorAll("[data-run]").forEach(b=>b.onclick=async()=>{selectedSkill=b.dataset.run;try{message.textContent="Running…";const r=await window.saeed.learning.run(selectedSkill);message.textContent=r.approved===false?"Skill cancelled.":"Skill completed."}catch(e){message.textContent=e.message}});
list.querySelectorAll("[data-toggle]").forEach(b=>b.onclick=async()=>{try{await window.saeed.learning.enable(b.dataset.toggle,b.textContent==="Enable");load()}catch(e){message.textContent=e.message}});
list.querySelectorAll("[data-remove]").forEach(b=>b.onclick=async()=>{if(confirm("Delete "+b.dataset.remove+"?")){await window.saeed.learning.remove(b.dataset.remove);load()}})}
async function load(){try{render(await window.saeed.learning.list())}catch(e){message.textContent=e.message}}
$("record").onclick=async()=>{try{if(!recording){const name=$("name").value.trim();if(!name)throw new Error("Enter a skill name first");const phrases=$("phrases").value.split("|").map(x=>x.trim()).filter(Boolean);await window.saeed.learning.recordStart(name,phrases);recording=true;$("record").textContent="Stop recording";$("recording").textContent="Recording Saeed tool actions…"}else{await window.saeed.learning.recordStop();recording=false;$("record").textContent="Start recording";$("recording").textContent="Recording saved.";load()}}catch(e){message.textContent=e.message}};
$("save").onclick=async()=>{try{const name=$("name").value.trim(),phrases=$("phrases").value.split("|").map(x=>x.trim()).filter(Boolean),raw=$("steps").value.trim();if(!name)throw new Error("Skill name is required");const steps=raw?JSON.parse(raw):[];await window.saeed.learning.save({name,id:name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,48),trigger:{phrases},steps});message.textContent="Skill saved.";load()}catch(e){message.textContent=e.message}};
$("clear").onclick=()=>{for(const id of ["name","phrases","steps"])$(id).value="";message.textContent=""};$("refresh").onclick=load;
$("export").onclick=async()=>{if(!selectedSkill){message.textContent="Select a skill first.";return}const data=await window.saeed.learning.export(selectedSkill);const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type:"application/json"}));a.download=selectedSkill+".json";a.click();URL.revokeObjectURL(a.href)};
$("import").onclick=()=>$("file").click();$("file").onchange=async()=>{const f=$("file").files[0];if(!f)return;try{await window.saeed.learning.import(await f.text());message.textContent="Skill imported.";load()}catch(e){message.textContent=e.message}$("file").value=""};addEventListener("load",load);