const {LocalBrain}=require("../../local-brain");
const {ApiBrain}=require("./api-brain");
const learning=require("../../learning");
class Brain{
 constructor({registry,getSettings,getDir,onEvent,requestStepIncrease,providerDefaults,memoryContext,saveHistory,baseStepLimit}={}){this.registry=registry;this.getSettings=getSettings||(()=>({}));this.getDir=getDir||(()=>process.cwd());this.onEvent=onEvent||(()=>{});this.requestStepIncrease=requestStepIncrease|| (async()=>false);this.providerDefaults=providerDefaults||(()=>({}));this.memoryContext=memoryContext||(()=> "");this.saveHistory=saveHistory||(()=>{});this.baseStepLimit=baseStepLimit||(()=>16);this.local=new LocalBrain(registry,this.onEvent);this.api=new ApiBrain()}
 capabilities(){return this.registry?.schemas?.().map(x=>x?.function?.name).filter(Boolean)||[]}
 async classify(text){const s=String(text||"").trim(),settings=this.getSettings()||{},mode=String(settings.brainMode||"auto"),skills=learning.list(this.getDir()),learned=skills.find(x=>x?.enabled!==false&&(x.trigger?.phrases||[]).some(p=>String(p).trim().toLowerCase()===s.toLowerCase()));if(learned)return{level:1,name:"learned-skill",reason:"exact-learned-skill",skill:learned.id,skillName:learned.name};if(mode==="local")return{level:1,name:"local",reason:"forced-local",capabilities:this.capabilities()};if(mode==="api"||mode==="realtime")return{level:3,name:"api",reason:mode==="realtime"?"realtime":"forced-api",capabilities:this.capabilities()};return{level:1,name:"local",reason:"local-first",capabilities:this.capabilities()}}
 async run({text,image=null,history=[]}={}){const s=String(text||"").trim(),settings=this.getSettings()||{},mode=String(settings.brainMode||"auto");if(!s)return{handled:true,answer:"Please tell me what you want me to do.",source:"empty"};const learned=learning.match(this.getDir(),s);if(learned){try{const result=await learning.run(this.getDir(),this.registry,learned);return{handled:true,answer:"Done — I followed the learned skill: "+learned.name+".",source:"learned-skill",event:{type:"learned-skill",skill:learned.id,name:learned.name,result}}}catch(e){this.onEvent({type:"diagnostic",level:"ERROR",stage:"LEARNED SKILL",message:e.message,meta:{skill:learned.id}})}}if(mode==="realtime")return{handled:true,answer:"Realtime mode is active. Use the microphone for the live conversation.",source:"realtime"};if(mode!=="api"){try{const local=await this.local.handle(s);if(local!==null)return{handled:true,answer:local,source:"local-brain"}}catch(e){this.onEvent({type:"diagnostic",level:"ERROR",stage:"BRAIN LOCAL",message:e.message})}}if(mode==="local")return{handled:true,answer:"I can handle common Windows computer tasks offline, but this request needs the API brain.",source:"local-fallback"};const route=await this.classify(s);this.onEvent({type:"diagnostic",level:"INFO",stage:"BRAIN ROUTE",message:"Single brain route selected: "+route.name,meta:route});const answer=await this.api.run({text:s,image,settings,history,registry:this.registry,onEvent:this.onEvent,dir:this.getDir(),route,memoryContext:this.memoryContext,saveHistory:this.saveHistory,baseStepLimit:this.baseStepLimit,askForMoreSteps:(current,task)=>this.requestStepIncrease({current,task}),providerDefaults:this.providerDefaults});return{handled:false,answer,source:"api"}}
}
module.exports={Brain};