const {spawn}=require("child_process");
function run(args){return new Promise((resolve,reject)=>{const p=spawn("cmdkey.exe",args,{windowsHide:true});let out="",err="";p.stdout.on("data",d=>out+=d);p.stderr.on("data",d=>err+=d);p.on("error",reject);p.on("close",c=>c===0?resolve(out):reject(new Error(err||"Credential Manager operation failed")))})}
function target(provider,account){return "Saeed:"+String(provider)+":"+String(account)}
async function set(provider,account,username,password){if(process.platform!=="win32")throw new Error("Windows Credential Manager is only available on Windows");await run(["/generic:"+target(provider,account),"/user:"+String(username),"/pass:"+String(password)]);return{provider,account,username,stored:true}}
async function remove(provider,account){if(process.platform!=="win32")return false;try{await run(["/delete:"+target(provider,account)]);return true}catch{return false}}
async function exists(provider,account){if(process.platform!=="win32")return false;try{await run(["/list:"+target(provider,account)]);return true}catch{return false}}
async function get(provider,account){if(process.platform!=="win32")throw new Error("Windows Credential Manager is only available on Windows");const t=target(provider,account);const script="$ErrorActionPreference='Stop';Add-Type @'\nusing System;using System.Runtime.InteropServices;using System.Text;\npublic static class CredNative{[StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)] public struct C{public int Type;public string TargetName;public string Comment;public System.Runtime.InteropServices.ComTypes.FILETIME LastWritten;public int BlobSize;public IntPtr Blob;public int Persist;public int AttributeCount;public IntPtr Attributes;public string TargetAlias;public string UserName;}[DllImport(\"advapi32.dll\",CharSet=CharSet.Unicode,SetLastError=true)] public static extern bool CredRead(string Target,int Type,int Flags,out IntPtr Credential);[DllImport(\"advapi32.dll\")] public static extern void CredFree(IntPtr Credential);}\n'@;$p=[IntPtr]::Zero;if(-not [CredNative]::CredRead('$t',1,0,[ref]$p)){throw 'Credential not found'};try{$c=[Runtime.InteropServices.Marshal]::PtrToStructure($p,[type][CredNative+C]);$pw=[Text.Encoding]::Unicode.GetString([byte[]](0..($c.BlobSize-1)|%{[Runtime.InteropServices.Marshal]::ReadByte($c.Blob,$_) }));[pscustomobject]@{username=$c.UserName;password=$pw}|ConvertTo-Json -Compress}finally{[CredNative]::CredFree($p)}";
return new Promise((resolve,reject)=>{const ps=spawn("powershell.exe",["-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-Command",script],{windowsHide:true});let out="",err="";ps.stdout.on("data",d=>out+=d);ps.stderr.on("data",d=>err+=d);ps.on("error",reject);ps.on("close",c=>{if(c!==0)return reject(new Error(err||"Credential not found"));try{resolve(JSON.parse(out.trim()))}catch{reject(new Error("Credential read failed"))}})})}
module.exports={target,set,remove,exists,get};
