const {spawn}=require("child_process");
function run(args){return new Promise((resolve,reject)=>{const p=spawn("cmdkey.exe",args,{windowsHide:true});let out="",err="";p.stdout.on("data",d=>out+=d);p.stderr.on("data",d=>err+=d);p.on("error",reject);p.on("close",c=>c===0?resolve(out):reject(new Error(err||"Credential Manager operation failed")))})}
function target(provider,account){return "Saeed:"+String(provider)+":"+String(account)}
async function set(provider,account,username,password){
 if(process.platform!=="win32")throw new Error("Windows Credential Manager is only available on Windows");
 const script="$ErrorActionPreference='Stop';$d=[Console]::In.ReadToEnd()|ConvertFrom-Json;Add-Type -TypeDefinition @'\nusing System;using System.Runtime.InteropServices;using System.Runtime.InteropServices.ComTypes;\npublic static class SaeedCredentialNative{[StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)] public struct CREDENTIAL{public UInt32 Flags;public UInt32 Type;public string TargetName;public string Comment;public FILETIME LastWritten;public UInt32 CredentialBlobSize;public IntPtr CredentialBlob;public UInt32 Persist;public UInt32 AttributeCount;public IntPtr Attributes;public string TargetAlias;public string UserName;}[DllImport(\"advapi32.dll\",CharSet=CharSet.Unicode,SetLastError=true)]public static extern bool CredWrite(ref CREDENTIAL credential,UInt32 flags);}\n'@;$b=[Text.Encoding]::Unicode.GetBytes([string]$d.password);$p=[Runtime.InteropServices.Marshal]::AllocHGlobal($b.Length);[Runtime.InteropServices.Marshal]::Copy($b,0,$p,$b.Length);try{$c=New-Object 'SaeedCredentialNative+CREDENTIAL';$c.Type=1;$c.TargetName=[string]$d.target;$c.Comment='Saeed email credential';$c.CredentialBlobSize=[uint32]$b.Length;$c.CredentialBlob=$p;$c.Persist=2;$c.UserName=[string]$d.username;if(-not [SaeedCredentialNative]::CredWrite([ref]$c,0)){throw ('Credential Manager write failed: '+[Runtime.InteropServices.Marshal]::GetLastWin32Error())};'stored'}finally{[Array]::Clear($b,0,$b.Length);$z=New-Object byte[] $b.Length;[Runtime.InteropServices.Marshal]::Copy($z,0,$p,$z.Length);[Runtime.InteropServices.Marshal]::FreeHGlobal($p)}";
 return new Promise((resolve,reject)=>{
  const child=spawn("powershell.exe",["-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-Command",script],{windowsHide:true,stdio:["pipe","pipe","pipe"]});
  let out="",err="";child.stdout.on("data",d=>out+=d);child.stderr.on("data",d=>err+=d);
  child.on("error",reject);child.on("close",code=>code===0&&out.trim()==="stored"?resolve({provider,account,username,stored:true}):reject(new Error(err||"Credential Manager write failed")));
  child.stdin.end(JSON.stringify({target:target(provider,account),username:String(username),password:String(password)}));
 });
}
async function remove(provider,account){if(process.platform!=="win32")return false;try{await run(["/delete:"+target(provider,account)]);return true}catch{return false}}
async function exists(provider,account){if(process.platform!=="win32")return false;try{await run(["/list:"+target(provider,account)]);return true}catch{return false}}
async function get(provider,account){if(process.platform!=="win32")throw new Error("Windows Credential Manager is only available on Windows");const t=target(provider,account);const script="$ErrorActionPreference='Stop';Add-Type @'\nusing System;using System.Runtime.InteropServices;using System.Text;\npublic static class CredNative{[StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)] public struct C{public UInt32 Flags;public UInt32 Type;public string TargetName;public string Comment;public System.Runtime.InteropServices.ComTypes.FILETIME LastWritten;public UInt32 BlobSize;public IntPtr Blob;public UInt32 Persist;public UInt32 AttributeCount;public IntPtr Attributes;public string TargetAlias;public string UserName;}[DllImport(\"advapi32.dll\",CharSet=CharSet.Unicode,SetLastError=true)] public static extern bool CredRead(string Target,int Type,int Flags,out IntPtr Credential);[DllImport(\"advapi32.dll\")] public static extern void CredFree(IntPtr Credential);}\n'@;$p=[IntPtr]::Zero;if(-not [CredNative]::CredRead('$t',1,0,[ref]$p)){throw 'Credential not found'};try{$c=[Runtime.InteropServices.Marshal]::PtrToStructure($p,[type][CredNative+C]);$pw=[Text.Encoding]::Unicode.GetString([byte[]](0..($c.BlobSize-1)|%{[Runtime.InteropServices.Marshal]::ReadByte($c.Blob,$_) }));[pscustomobject]@{username=$c.UserName;password=$pw}|ConvertTo-Json -Compress}finally{[CredNative]::CredFree($p)}";
return new Promise((resolve,reject)=>{const ps=spawn("powershell.exe",["-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-Command",script],{windowsHide:true});let out="",err="";ps.stdout.on("data",d=>out+=d);ps.stderr.on("data",d=>err+=d);ps.on("error",reject);ps.on("close",c=>{if(c!==0)return reject(new Error(err||"Credential not found"));try{resolve(JSON.parse(out.trim()))}catch{reject(new Error("Credential read failed"))}})})}
module.exports={target,set,remove,exists,get};
