const net=require("net"),tls=require("tls");
function lineConnection(socket){let buffer="",waiters=[];const next=()=>new Promise((resolve,reject)=>waiters.push({resolve,reject}));socket.on("data",d=>{buffer+=String(d);let i;while((i=buffer.indexOf("\r\n"))>=0){const line=buffer.slice(0,i);buffer=buffer.slice(i+2);const w=waiters.shift();if(w)w.resolve(line)}});socket.on("error",e=>{for(const w of waiters.splice(0))w.reject(e)});socket.setTimeout(20000,()=>socket.destroy(new Error("Email connection timed out")));return{socket,next,command:async x=>{socket.write(String(x)+"\r\n");return next()}}}
function connect(config,{tlsMode=config.tls}={}){return new Promise((resolve,reject)=>{const opts={host:config.host,port:Number(config.port),servername:config.host,rejectUnauthorized:true};const socket=tlsMode?tls.connect(opts):net.connect(opts);socket.once("connect",()=>resolve(lineConnection(socket)));socket.once("secureConnect",()=>resolve(lineConnection(socket)));socket.once("error",reject)})}
async function smtpSend(config,msg){let c=await connect(config,{tlsMode:Boolean(config.tls)});let r=await c.next();if(!/^2/.test(r))throw new Error(r);let eh=await c.command("EHLO saeed");if(config.startTls&&!config.tls){if(!/^2/.test(eh))throw new Error(eh);r=await c.command("STARTTLS");if(!/^2/.test(r))throw new Error(r);const old=c.socket;const secure=tls.connect({socket:old,servername:config.host,rejectUnauthorized:true});c=lineConnection(secure);await c.next();eh=await c.command("EHLO saeed")}if(!/^2/.test(eh))throw new Error(eh);
if(config.accessToken){r=await c.command("AUTH XOAUTH2 "+Buffer.from("user="+config.username+"\x01auth=Bearer "+config.accessToken+"\x01\x01").toString("base64"));if(!/^2/.test(r))throw new Error(r)}
else if(config.username){r=await c.command("AUTH LOGIN");if(!/^3/.test(r))throw new Error(r);r=await c.command(Buffer.from(config.username).toString("base64"));if(!/^3/.test(r))throw new Error(r);r=await c.command(Buffer.from(config.password||"").toString("base64"));if(!/^2/.test(r))throw new Error(r)}
r=await c.command("MAIL FROM:<"+config.from+">");if(!/^2/.test(r))throw new Error(r);for(const to of [].concat(config.to||[])){r=await c.command("RCPT TO:<"+to+">");if(!/^2/.test(r))throw new Error(r)}r=await c.command("DATA");if(!/^3/.test(r))throw new Error(r);c.socket.write(String(msg).replace(/^\./gm,"..")+"\r\n.\r\n");r=await c.next();try{await c.command("QUIT")}catch{}c.socket.destroy();if(!/^2/.test(r))throw new Error(r);return true}
async function pop3List(config){const c=await connect(config);let r=await c.next();if(!/^\+OK/.test(r))throw new Error(r);r=await c.command("USER "+config.username);if(!/^\+OK/.test(r))throw new Error(r);r=await c.command("PASS "+config.password);if(!/^\+OK/.test(r))throw new Error(r);const stat=await c.command("STAT");try{await c.command("QUIT")}catch{}c.socket.destroy();return stat}
async function pop3Fetch(config,index){const c=await connect(config);let r=await c.next();if(!/^\+OK/.test(r))throw new Error(r);for(const cmd of ["USER "+config.username,"PASS "+config.password]){r=await c.command(cmd);if(!/^\+OK/.test(r))throw new Error(r)}c.socket.write("RETR "+Number(index)+"\r\n");let lines=[];while(true){const line=await c.next();if(line===".")break;lines.push(line.replace(/^\.\./,"."))}try{await c.command("QUIT")}catch{}c.socket.destroy();return lines.join("\r\n")}
async function imapProbe(config){const c=await connect(config);let r=await c.next();if(!/^\*/.test(r))throw new Error(r);const tag="A"+Date.now().toString(36).toUpperCase();c.socket.write(tag+" CAPABILITY\r\n");let lines=[];while(true){const line=await c.next();lines.push(line);if(line.startsWith(tag+" "))break}c.socket.write("A2 LOGOUT\r\n");c.socket.destroy();return lines.join("\n")}
async function imapLogin(config){const c=await connect(config);let r=await c.next();if(!/^\*/.test(r))throw new Error(r);const tag="A1";c.socket.write(config.accessToken?tag+" AUTHENTICATE XOAUTH2\r\n":tag+" LOGIN \""+String(config.username).replace(/"/g,'\"')+"\" \""+String(config.password||"").replace(/"/g,'\"')+"\"\r\n");r=await c.next();if(!/^A1 (OK)/.test(r))throw new Error(r);c.socket.destroy();return true}
module.exports={smtpSend,pop3List,pop3Fetch,imapProbe,imapLogin};
