const $=id=>document.getElementById(id),list=$("list"),message=$("message");let catalog=[],installed=[];
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
const categoryOrder=["Documents","Office","Computer","Brain","Memory","Speech to Text","Speech to Speech","Vision","Browser","Code","Communication","Storage","Other"];
function categoryOf(a){const c=String(a.category||"Other");return categoryOrder.includes(c)?c:"Other"}
function render(){const q=String($("search").value||"").trim().toLowerCase(),only=$("enabledOnly").checked,map=new Map(installed.map(x=>[x.id,x]));const groups=new Map();for(const a of catalog){const item=map.get(a.id),hay=[a.name,a.description,a.category,...(a.capabilities||[])].join(" ").toLowerCase();if(q&&!hay.includes(q))continue;if(only&&!(item?.enabled!==false))continue;const cat=categoryOf(a);if(!groups.has(cat))groups.set(cat,[]);groups.get(cat).push(a)}
const ordered=[...categoryOrder,...[...groups.keys()].filter(x=>!categoryOrder.includes(x))];list.innerHTML=ordered.filter(c=>groups.has(c)).map(c=>{const items=groups.get(c);return '<section class="group"><div class="groupTitle">'+esc(c)+' <span>'+items.length+'</span></div>'+items.map(a=>{const item=map.get(a.id),on=!!item,enabled=item?.enabled!==false,ready=Boolean(a.downloadUrl||a.installType==="npm-package");return '<article class="addon '+(on?"installed":"")+'"><div class="addonHead"><button class="chevron" aria-label="Details">⌄</button><div class="addonTitle"><b>'+esc(a.name)+'</b><small>'+esc(a.version)+' · '+esc(a.provider||"Saeed")+'</small></div><div class="addonSize">'+esc(a.size||"On demand")+'</div><div class="state">'+(on?(enabled?"Enabled":"Disabled"):(ready?"Available":"Not packaged"))+'</div><button class="action" data-action="'+(on?"toggle":"install")+'" data-id="'+esc(a.id)+'">'+(on?(enabled?"Disable":"Enable"):(ready?"Install":"Unavailable"))+'</button></div><div class="addonDetails"><p>'+esc(a.description||"")+'</p><div class="caps">'+esc((a.capabilities||[]).join(" · "))+'</div>'+(a.sourceUrl?'<a href="'+esc(a.sourceUrl)+'" target="_blank">Documentation / source</a>':"")+(on?'<button class="link danger" data-action="uninstall" data-id="'+esc(a.id)+'">Uninstall</button>':"")+'<div class="progress"><i id="p-'+esc(a.id)+'"></i></div><div id="e-'+esc(a.id)+'" class="error"></div></div></article>'}).join("")+'</section>'}).join("")||'<div class="empty">No add-ons match your search.</div>';
list.querySelectorAll(".chevron").forEach(b=>b.onclick=()=>b.closest(".addon").classList.toggle("open"));list.querySelectorAll(".addonHead").forEach(h=>h.ondblclick=()=>h.closest(".addon").classList.toggle("open"));list.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset.id))}
async function load(){try{const r=await window.saeed.addons.catalog();catalog=r.catalog?.addons||[];installed=r.installed||[];render()}catch(e){message.textContent=e.message}}
async function action(kind,id){try{if(kind==="install"){const p=$("p-"+id),e=$("e-"+id);p.style.width="2%";e.textContent="";message.textContent="Installing "+id+"…";await window.saeed.addons.install(id,s=>{if(s?.percent!=null)p.style.width=Math.max(2,Math.min(100,s.percent))+"%"});message.textContent=id+" installed.";await load()}else if(kind==="toggle"){const item=installed.find(x=>x.id===id);await window.saeed.addons.enable(id,item?.enabled===false);await load()}else if(kind==="uninstall"){if(confirm("Uninstall "+id+"?")){await window.saeed.addons.uninstall(id);await load()}}}catch(e){const el=$("e-"+id);if(el)el.textContent=e.message;message.textContent="Operation failed: "+e.message}}
$("search").oninput=render;$("enabledOnly").onchange=render;$("refresh").onclick=load;window.saeed.onAddonsRefresh?.(load);window.addEventListener("load",load);