const fs=require("fs"),path=require("path"),{safeStorage}=require("electron");
const DEFAULT_PERMISSIONS={files:"allow",applications:"allow",system:"allow",network:"allow",screen:"allow",mouseKeyboard:"allow",microphone:"allow",tasksMemory:"allow",credentials:"allow",destructive:"allow"};
const DEFAULTS={provider:"openai",baseUrl:"https://api.openai.com/v1",model:"gpt-5",apiKey:"",maxSteps:16,agentExtraSteps:"ask",brainMode:"auto",sttProvider:"whisper",sttModel:"base-q5_1",sttLanguage:"auto",streamingMode:"off",voiceControlVersion:3,ttsProvider:"local",ttsModel:"gpt-4o-mini-tts",ttsVoice:"alloy",sttBaseUrl:"",ttsBaseUrl:"",voiceProfile:"saeed",showSpeechText:false,language:"en",permissions:DEFAULT_PERMISSIONS,realtimeProvider:"openai",realtimeModel:"gpt-realtime-2.1",realtimeVoice:"marin",micSpeechRms:0.09,micInterruptRms:0.09,voiceMuted:false,apiServices:{brain:true,stt:true,tts:true},realtimeBrainMode:"auto",characterSize:"small",characterBehavior:{breathing:true,blinking:true,expressions:true,speechFace:true,idle:true,walking:true,dancing:true,greeting:true,events:true,random:true,frequency:"normal",eventCooldownSec:30,autonomousMovement:true,idleThoughts:true,sleep:true,eyeTracking:true,sleepAfterMin:20,renderWakeMs:1200}};
class SettingsStore{
 constructor(dir){this.dir=dir;this.file=path.join(dir,"settings.json");fs.mkdirSync(dir,{recursive:true})}
 read(){try{return JSON.parse(fs.readFileSync(this.file,"utf8"))}catch{return{}}}
 decrypt(v){try{return v&&safeStorage.isEncryptionAvailable()?safeStorage.decryptString(Buffer.from(v,"base64")):String(v||"")}catch{return String(v||"")}}
 encrypt(v){try{return v&&safeStorage.isEncryptionAvailable()?safeStorage.encryptString(String(v)).toString("base64"):String(v||"")}catch{return String(v||"")}}
 load(){const raw=this.read();return{...DEFAULTS,...raw,permissions:{...DEFAULT_PERMISSIONS,...(raw.permissions||{})},characterBehavior:{...DEFAULTS.characterBehavior,...(raw.characterBehavior||{})},apiServices:{brain:true,stt:true,tts:true,...(raw.apiServices||{})},micMode:"off",brainMode:["api","local","auto"].includes(String(raw.brainMode||""))?String(raw.brainMode):"auto",apiKey:this.decrypt(raw.apiKey),sttApiKey:this.decrypt(raw.sttApiKey),ttsApiKey:this.decrypt(raw.ttsApiKey),realtimeApiKey:this.decrypt(raw.realtimeApiKey)}}
 providerDefaults(name){return{openai:{baseUrl:"https://api.openai.com/v1",model:"gpt-5"},anthropic:{baseUrl:"https://api.anthropic.com/v1",model:"claude-sonnet-4-5"},gemini:{baseUrl:"https://generativelanguage.googleapis.com/v1beta/openai",model:"gemini-2.5-pro"},groq:{baseUrl:"https://api.groq.com/openai/v1",model:"openai/gpt-oss-120b"},"openai-compatible":{baseUrl:"",model:""}}[name]||{}}
 apply(previous,input){const next={...previous,...(input||{}),permissions:{...previous.permissions,...(input?.permissions||{})},characterBehavior:{...previous.characterBehavior,...(input?.characterBehavior||{})}};next.brainMode=["api","local","auto"].includes(String(next.brainMode||""))?String(next.brainMode):String(previous.brainMode||"auto");next.apiServices={brain:next.apiServices?.brain!==false,stt:next.apiServices?.stt!==false,tts:next.apiServices?.tts!==false};next.realtimeBrainMode=["saeed","api","auto"].includes(String(next.realtimeBrainMode||""))?String(next.realtimeBrainMode):"auto";next.maxSteps=Math.max(1,Math.min(100,Number(next.maxSteps)||16));next.agentExtraSteps=next.agentExtraSteps==="allow"?"allow":"ask";delete next.alwaysListening;if(input?.clearLlmKey){next.apiKey="";delete next.clearLlmKey}if(input?.clearAllApiKeys){next.apiKey="";next.sttApiKey="";next.ttsApiKey="";next.realtimeApiKey="";delete next.clearAllApiKeys}for(const k of ["apiKey","sttApiKey","ttsApiKey","realtimeApiKey"])if(input&&input[k]==="")next[k]=previous[k]||"";if(input?.provider&&input.provider!==previous.provider){const p=this.providerDefaults(input.provider);if(input.baseUrl===undefined||input.baseUrl===previous.baseUrl)next.baseUrl=p.baseUrl;if(input.model===undefined||input.model===previous.model)next.model=p.model}const p=this.providerDefaults(next.provider);if(!next.sttBaseUrl)next.sttBaseUrl="";if(!next.ttsBaseUrl)next.ttsBaseUrl="";if(!next.baseUrl)next.baseUrl=p.baseUrl;if(!next.model)next.model=p.model;this.persist(next);return next}
 persist(s){try{fs.writeFileSync(this.file,JSON.stringify({...s,apiKey:this.encrypt(s.apiKey),sttApiKey:this.encrypt(s.sttApiKey),ttsApiKey:this.encrypt(s.ttsApiKey),realtimeApiKey:this.encrypt(s.realtimeApiKey)},null,2))}catch(e){console.error("Settings save failed:",e)}}
 public(s){const out={...s};delete out.alwaysListening;return{...out,apiKey:"",sttApiKey:"",ttsApiKey:"",realtimeApiKey:"",hasApiKey:Boolean(s.apiKey),hasSttApiKey:Boolean(s.sttApiKey),hasTtsApiKey:Boolean(s.ttsApiKey),hasRealtimeApiKey:Boolean(s.realtimeApiKey)}}
}
function createSettingsStore(dir){return new SettingsStore(dir)}
module.exports={SettingsStore,createSettingsStore};