const fs=require("fs"),path=require("path");
const {MAX_ARCHIVE_BYTES,validateArchive}=require("../conversation/archive");
function registerHistoryIpc({ipcMain,getAgent,getChatWindow,getConfirmations,dialog}){
 ipcMain.handle("history:get",()=>getAgent()?.history||[]);ipcMain.handle("chat:list",()=>getAgent()?.listConversations?.()||[]);ipcMain.handle("chat:current",()=>getAgent()?.getCurrentConversation?.()||null);ipcMain.handle("chat:memory",()=>getAgent()?.getGlobalMemory?.()||[]);
 ipcMain.handle("chat:new",()=>{const agent=getAgent();if(!agent)return null;const chat=agent.newConversation();getChatWindow()?.webContents.send("chat:switched",chat,[]);return{chat,history:[]}});
 ipcMain.handle("chat:select",(_,id)=>{const agent=getAgent();if(!agent)return null;const chat=agent.selectConversation(String(id||""));if(!chat)return null;const history=agent.history||[];getChatWindow()?.webContents.send("chat:switched",chat,history);return{chat,history}});
 ipcMain.handle("chat:delete",(_,id)=>{const agent=getAgent();if(!agent)return null;const result=agent.deleteConversation(String(id||""));if(!result)return null;getChatWindow()?.webContents.send("chat:switched",result.chat,result.history);return result});
 ipcMain.handle("history:clear",()=>{const agent=getAgent();if(!agent)return false;agent.clearHistory();getChatWindow()?.webContents.send("history:cleared");return true});
 ipcMain.handle("chat:export-conversations",async()=>{const agent=getAgent();if(!agent)return{ok:false,error:"Conversation service is not available"};if(!dialog?.showSaveDialog)return{ok:false,error:"File save dialog is not available"};const archive=agent.exportConversationsArchive(),stamp=new Date().toISOString().replace(/[:.]/g,"-"),choice=await dialog.showSaveDialog({title:"Export Saeed conversations",defaultPath:"Saeed-conversations-"+stamp+".json",filters:[{name:"Saeed conversation archive",extensions:["json"]}]});if(choice.canceled||!choice.filePath)return{ok:false,canceled:true};const target=path.resolve(choice.filePath),temp=target+".tmp-"+process.pid;try{const json=JSON.stringify(archive,null,2);if(Buffer.byteLength(json,"utf8")>MAX_ARCHIVE_BYTES)throw new Error("Archive exceeds the 10 MB limit");fs.writeFileSync(temp,json,{encoding:"utf8",flag:"wx"});validateArchive(fs.readFileSync(temp,"utf8"));fs.renameSync(temp,target);const verified=validateArchive(fs.readFileSync(target,"utf8"));return{ok:true,path:target,conversationCount:verified.conversations.length}}catch(error){try{fs.unlinkSync(temp)}catch{}return{ok:false,error:error?.message||String(error)}}});
 ipcMain.handle("chat:import-conversations",async()=>{const agent=getAgent();if(!agent)return{ok:false,error:"Conversation service is not available"};if(!dialog?.showOpenDialog)return{ok:false,error:"File open dialog is not available"};const choice=await dialog.showOpenDialog({title:"Import Saeed conversations",properties:["openFile"],filters:[{name:"Saeed conversation archive",extensions:["json"]}]});if(choice.canceled||!choice.filePaths?.length)return{ok:false,canceled:true};try{const file=choice.filePaths[0],stat=fs.statSync(file);if(!stat.isFile()||stat.size>MAX_ARCHIVE_BYTES)throw new Error("Archive must be a regular JSON file no larger than 10 MB");const input=fs.readFileSync(file,"utf8");validateArchive(input);const result=agent.importConversationsArchive(input);getChatWindow()?.webContents.send("chat:archive-imported",result);return result}catch(error){return{ok:false,error:error?.message||String(error)}}});
 ipcMain.handle("agent:confirm-response",(_,id,approved)=>getConfirmations().has(String(id))?(getConfirmations().get(String(id))(Boolean(approved)),getConfirmations().delete(String(id)),true):false);
}
module.exports={registerHistoryIpc};
