function registerVoiceIpc({ipcMain,getAgent,diagnostic,app,getVoiceHost,getBrainHost,diagnosticState,getStatusWindow,getThreeDStatusWindow,getCharacterWindow,getChatWindow}){
 const setMicMode=(...args)=>getVoiceHost().setMicMode(...args);
 const setVoiceMuted=(...args)=>getVoiceHost().setVoiceMuted(...args);
 const transcribeLocalWav=(...args)=>getVoiceHost().transcribeLocalWav(...args);
 function provider(kind,s){const p=String(s?.[kind+"Provider"]||"local");if(kind==="tts")return p==="openai"?{p,url:(s.ttsBaseUrl||"https://api.openai.com/v1")+"/audio/speech",key:s.ttsApiKey||s.apiKey,model:s.ttsModel||"gpt-4o-mini-tts",voice:s.ttsVoice||"alloy"}:p==="groq"?{p,url:(s.ttsBaseUrl||"https://api.groq.com/openai/v1")+"/audio/speech",key:s.ttsApiKey,model:s.ttsModel||"canopylabs/orpheus-v1-english",voice:s.ttsVoice||"austin"}:p==="elevenlabs"?{p,url:(s.ttsBaseUrl||"https://api.elevenlabs.io/v1")+"/text-to-speech/"+encodeURIComponent(s.ttsVoice||"JBFqnCBsd6RMkjVDRZzb"),key:s.ttsApiKey,model:s.ttsModel||"eleven_flash_v2_5",voice:s.ttsVoice}:{p};const base=String(s?.sttBaseUrl|| (p==="openai"?"https://api.openai.com/v1":p==="groq"?"https://api.groq.com/openai/v1":"https://api.elevenlabs.io/v1")).replace(/\\/+$/,"");return p==="openai"?{p,url:base+"/audio/transcriptions",key:s.sttApiKey||s.apiKey,model:s.sttModel||"gpt-4o-mini-transcribe"}:p==="groq"?{p,url:base+"/audio/transcriptions",key:s.sttApiKey,model:s.sttModel||"whisper-large-v3-turbo"}:p==="elevenlabs"?{p,url:base+"/speech-to-text",key:s.sttApiKey,model:s.sttModel||"scribe_v2"}:{p}}
 function wav(base64){const pcm=Buffer.from(String(base64||""),"base64"),h=Buffer.alloc(44);h.write("RIFF",0);h.writeUInt32LE(36+pcm.length,4);h.write("WAVE",8);h.write("fmt ",12);h.writeUInt32LE(16,16);h.writeUInt16LE(1,20);h.writeUInt16LE(1,22);h.writeUInt32LE(24000,24);h.writeUInt32LE(48000,28);h.writeUInt16LE(2,32);h.writeUInt16LE(16,34);h.write("data",36);h.writeUInt32LE(pcm.length,40);return Buffer.concat([h,pcm])}
 ipcMain.handle("voice:chat",async(_,text)=>{const input=String(text||"").trim();if(!input)return "";const agent=getAgent();if(!agent?.runVoice)return "";const brainHost=getBrainHost?.();brainHost?.beginRequest?.();try{return await agent.runVoice(input)}catch(e){diagnostic("ERROR","VOICE BRAIN",e.message);throw e}finally{brainHost?.endRequest?.()}});
 ipcMain.handle("voice:speak",async(event,text)=>{const input=String(text||"").trim();if(!input)return false;const character=getCharacterWindow?.(),chat=getChatWindow?.(),target=character&&!character.isDestroyed()&&character.isVisible()?character:chat&&!chat.isDestroyed()?chat:null;try{if(target)target.webContents.send("voice:speak",input);else if(event.sender&&!event.sender.isDestroyed())event.sender.send("voice:speak",input);else return false;return true}catch(e){diagnostic("ERROR","VOICE SPEAK",e.message);return false}});
 ipcMain.handle("tts:speak",async(_,text)=>{const s=getAgent()?.settings||{};if(s.apiServices?.tts===false)return{ok:false,error:"API TTS is disabled in Performance settings"};const c=provider("tts",s),input=String(text||"").trim();if(!input||c.p==="local")return{ok:false,reason:input?"tts-provider-local":"empty"};if(!c.key)return{ok:false,error:c.p.toUpperCase()+" TTS API key is missing"};try{const body=c.p==="elevenlabs"?{text:input,model_id:c.model}:{model:c.model,input,response_format:"wav",voice:c.voice};const headers=c.p==="elevenlabs"?{"xi-api-key":c.key,"Content-Type":"application/json"}:{"Authorization":"Bearer "+c.key,"Content-Type":"application/json"};const r=await fetch(c.url+(c.p==="elevenlabs"?"?output_format=mp3_44100_128":""),{method:"POST",headers,body:JSON.stringify(body),signal:AbortSignal.timeout(60000)});if(!r.ok)return{ok:false,error:c.p.toUpperCase()+" TTS HTTP "+r.status};return{ok:true,base64:Buffer.from(await r.arrayBuffer()).toString("base64")}}catch(e){diagnostic("ERROR","TTS API",e.message);return{ok:false,error:e.message}}});
 ipcMain.handle("stt:transcribe",async(_,base64)=>{const s=getAgent()?.settings||{};if(s.apiServices?.stt===false)return{ok:false,error:"API STT is disabled in Performance settings"};const c=provider("stt",s);if(c.p==="local")return{ok:false,reason:"stt-provider-local"};if(!c.key)return{ok:false,error:c.p.toUpperCase()+" STT API key is missing"};try{const form=new FormData();form.append("file",new Blob([wav(base64)],{type:"audio/wav"}),"saeed.wav");form.append(c.p==="elevenlabs"?"model_id":"model",c.model);if(s.sttLanguage&&s.sttLanguage!=="auto")form.append(c.p==="elevenlabs"?"language_code":"language",String(s.sttLanguage));const headers=c.p==="elevenlabs"?{"xi-api-key":c.key}:{"Authorization":"Bearer "+c.key};const r=await fetch(c.url,{method:"POST",headers,body:form,signal:AbortSignal.timeout(60000)}),body=await r.text();if(!r.ok){let detail=body;try{const parsed=JSON.parse(body);detail=parsed.error?.message||parsed.detail||parsed.message||body}catch{}return{ok:false,error:c.p.toUpperCase()+" STT HTTP "+r.status+": "+String(detail).slice(0,500)}}let j={};try{j=JSON.parse(body)}catch{}return{ok:true,text:String(j.text||body||"").trim()}}catch(e){diagnostic("ERROR","STT API",e.message);return{ok:false,error:e.message}}});
 ipcMain.handle("realtime:start",(_,options={})=>Boolean(getVoiceHost().getVoiceRuntime().start(options)));ipcMain.handle("realtime:stop",()=>{getVoiceHost().getVoiceRuntime().stop();return true});ipcMain.handle("realtime:audio",(_,b)=>{getVoiceHost().getVoiceRuntime().getRealtime()?.appendAudio(String(b||""));return true});ipcMain.handle("realtime:cancel",()=>{getVoiceHost().getVoiceRuntime().getRealtime()?.cancel();return true});ipcMain.handle("local-stt:transcribe",async(_,b)=>{try{return{ok:true,text:await transcribeLocalWav(String(b||""))}}catch(e){return{ok:false,error:e.message}}});
 ipcMain.handle("mic:mode",(_,mode)=>setMicMode(mode));ipcMain.handle("voice:mute",(_,muted)=>setVoiceMuted(Boolean(muted)));ipcMain.handle("api:clear-all",async()=>{const agent=getAgent();if(!agent)return null;try{getVoiceHost().stopVoiceServices?.("clear api")}catch{}try{await setMicMode("off")}catch{}agent.settings={clearAllApiKeys:true,clearKeys:["apiKey","sttApiKey","ttsApiKey","realtimeApiKey"],apiKey:"",sttApiKey:"",ttsApiKey:"",realtimeApiKey:""};return agent.publicSettings()});
 ipcMain.on("mic:level",(_,level)=>{const v=Math.max(0,Math.min(1,Number(level)||0));diagnosticState.mic={...diagnosticState.mic,state:v>0?"active":diagnosticState.mic.state,level:v,detail:"Live microphone input"};for(const win of [getStatusWindow(),getThreeDStatusWindow(),getCharacterWindow()])if(win&&!win.isDestroyed())win.webContents.send("mic:level",v)});
}
module.exports={registerVoiceIpc};