import * as THREE from "../node_modules/three/build/three.module.js";
import {GLTFLoader} from "./three/GLTFLoader.js";
const canvas=document.getElementById("avatar"),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(30,1,.01,100);
const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:"high-performance"});
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.setPixelRatio(Math.min(Math.max(1,devicePixelRatio||1),1.5));
scene.add(new THREE.HemisphereLight(0xffffff,0x334455,2.1));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(2,4,3);scene.add(key);
const root=new THREE.Group();scene.add(root),loader=new GLTFLoader(),viewSettings={characterScale:1,characterPositionX:0,characterPositionY:0,characterPositionZ:0,characterRotationY:0,canvasPadding:0};
let model=null,rig=new Map(),base=new Map(),morphs=new Map(),loadGeneration=0,activeLoad=false,pendingLoad=null,renderQueued=false;
function getBoneMap(){return Object.fromEntries(rig)}function getAvailableBoneNames(){const a=[];model?.traverse(o=>{if(o.isBone)a.push(o.name)});return a}
function bindRig(mapping={}){if(!model)return false;const by={};model.traverse(o=>{if(o.isBone)by[String(o.name).toLowerCase()]=o});rig.clear();base.clear();for(const [slot,name] of Object.entries(mapping)){const b=by[String(name||"").toLowerCase()];if(b){rig.set(slot,b);base.set(slot,{x:b.rotation.x,y:b.rotation.y,z:b.rotation.z})}}resetCharacterPose();render();return rig.size>0}
function resetCharacterPose(){for(const [slot,b] of rig){const p=base.get(slot);if(p)b.rotation.set(p.x,p.y,p.z)}}
function applyCharacterPose(pose={},retargeter=null){for(const [slot,r] of Object.entries(pose)){if(retargeter?.apply?.(slot,r))continue;const b=rig.get(slot),p=base.get(slot);if(b&&p)b.rotation.set(p.x+(Number(r?.x)||0),p.y+(Number(r?.y)||0),p.z+(Number(r?.z)||0))}render();return true}
function applyRawBonePose(pose={}){for(const [name,r] of Object.entries(pose)){let b=null;model?.traverse(o=>{if(!b&&o.isBone&&String(o.name)===String(name))b=o});if(b){b.rotation.x+=Number(r?.x)||0;b.rotation.y+=Number(r?.y)||0;b.rotation.z+=Number(r?.z)||0}}render();return true}
function collectMorphs(){morphs=new Map();model?.traverse(o=>{if(!o.isMesh||!o.morphTargetDictionary||!o.morphTargetInfluences)return;for(const [name,i] of Object.entries(o.morphTargetDictionary)){const k=String(name).toLowerCase();if(!morphs.has(k))morphs.set(k,[]);morphs.get(k).push([o,i])}})}
function setMorph(name,value=0){const list=morphs.get(String(name||"").toLowerCase());if(!list)return false;const v=Math.max(0,Math.min(1,Number(value)||0));for(const [m,i] of list)m.morphTargetInfluences[i]=v;render();return true}
function blink(){for(const n of ["blink","eyeclose"])if(setMorph(n,1)){setTimeout(()=>setMorph(n,0),140);return true}return false}
function lookAt(x=0,y=1.5,z=1){const h=rig.get("head");if(!h)return false;const p=h.getWorldPosition(new THREE.Vector3()),d=new THREE.Vector3(Number(x)||0,Number(y)||0,Number(z)||0).sub(p).normalize(),b=base.get("head");if(b)h.rotation.set(b.x-Math.asin(Math.max(-1,Math.min(1,d.y)))*.45,b.y+Math.atan2(d.x,d.z)*.45,b.z);render();return true}
function dispose(o){o?.traverse?.(x=>{x.geometry?.dispose?.();const ms=Array.isArray(x.material)?x.material:[x.material];for(const m of ms){if(!m)continue;for(const k of ["map","normalMap","roughnessMap","metalnessMap","emissiveMap","aoMap","alphaMap"])m[k]?.dispose?.();m.dispose?.()}})}
function fit(){if(!model)return;model.updateWorldMatrix(true,true);const raw=new THREE.Box3().setFromObject(model,true),size=raw.getSize(new THREE.Vector3()),scale=3.75/Math.max(size.y,.001)*Number(viewSettings.characterScale||1);model.scale.setScalar(scale);model.position.set(Number(viewSettings.characterPositionX)||0,Number(viewSettings.characterPositionY)||0,Number(viewSettings.characterPositionZ)||0);model.rotation.y=Number(viewSettings.characterRotationY)||0;model.updateWorldMatrix(true,true);const box=new THREE.Box3().setFromObject(model,true),s=box.getSize(new THREE.Vector3()),c=box.getCenter(new THREE.Vector3()),aspect=Math.max(.1,(canvas.clientWidth||430)/(canvas.clientHeight||520)),vf=THREE.MathUtils.degToRad(camera.fov*.5),hf=2*Math.atan(Math.tan(vf)*aspect),dist=Math.max(s.y*.5/Math.tan(vf),s.x*.5/Math.tan(hf*.5))+s.z*.12;camera.position.set(c.x,c.y+Math.tan(THREE.MathUtils.degToRad(4))*dist,c.z+Math.max(1.05,dist*.82));camera.near=Math.max(.01,s.length()/1000);camera.far=Math.max(100,s.length()*12);camera.lookAt(c);camera.updateProjectionMatrix()}
function render(){if(renderQueued||document.hidden)return;renderQueued=true;requestAnimationFrame(()=>{renderQueued=false;renderer.render(scene,camera)})}
function resize(){const r=canvas.getBoundingClientRect(),w=Math.max(1,r.width),h=Math.max(1,r.height);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();fit();render()}new ResizeObserver(resize).observe(canvas);
function display(parsed){if(!parsed?.scene)throw new Error("Selected GLB contains no scene");if(model)dispose(model);root.clear();model=parsed.scene;root.add(model);rig.clear();base.clear();collectMorphs();fit();render();window.saeedCharacterController?.onCharacterLoaded?.()}
async function load(data,generation){activeLoad=true;try{const bytes=data instanceof ArrayBuffer?data:data instanceof Uint8Array?data.buffer:data?.buffer;if(!bytes)throw new Error("Selected GLB data is invalid");const parsed=await loader.parseAsync(bytes,"");if(generation===loadGeneration)display(parsed)}finally{activeLoad=false;if(pendingLoad){const p=pendingLoad;pendingLoad=null;void load(p.data,p.generation)}}}
window.saeedAvatarLoadData=async(data,generation)=>{const g=Number(generation)||++loadGeneration;loadGeneration=Math.max(loadGeneration,g);if(activeLoad){pendingLoad={data,generation:g};return}return load(data,g)};
window.saeedAvatarApply3DSettings=s=>{Object.assign(viewSettings,s||{});fit();render();return{...viewSettings}};window.saeedAvatarGet3DSettings=()=>({...viewSettings});window.saeedAvatarSetRuntimeActive=()=>true;
window.saeedAvatar={get3DStatus:()=>({overall:{state:model?"ready":"starting",detail:model?"3D character rendered":"Waiting for GLB"},components:{renderer:{state:"ready"},scene:{state:"ready"},camera:{state:"ready"},canvas:{state:"ready"},sceneContent:{state:model?"rendered":"waiting"}},metrics:{drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures}}),getBoneMap,getBones:getBoneMap,getAvailableBoneNames,bindRig,applyCharacterPose,resetCharacterPose,getCharacterProfileKey:()=>String(window.saeedAvatarCurrentName||"Saeed").trim(),getCharacterRigAutoMap:()=>Object.fromEntries([...rig].map(([k,b])=>[k,b.name])),applyRawBonePose,setCharacterExpression:setMorph,blinkCharacter:blink,setCharacterViseme:setMorph,lookCharacterAt:lookAt,wakeRender:render};
resize();