(()=>{
 const cleanText=t=>String(t||"").replace(/^[\s\.,!?؟،؛:]+/,"").trim();
 const report=(level,stage,message,meta)=>window.saeed?.reportDiagnostic?.(level,stage,message,meta);
 let mic=null,realtimeAssistant="",speechTimer=null;
 const phonemeMap={a:"aa",e:"ee",i:"ee",o:"oh",u:"oo",y:"ee",b:"mbp",m:"mbp",p:"mbp",f:"fv",v:"fv",q:"oh",w:"oo",j:"ee"};
 function stopSpeaking(){if("speechSynthesis"in window)window.speechSynthesis.cancel();if(speechTimer){clearInterval(speechTimer);speechTimer=null}["aa","ee","oo","oh","fv","mbp"].forEach(v=>window.saeedAvatar?.setViseme?.(v,0))}
 function speak(text){if(!text||!("speechSynthesis"in window))return;stopSpeaking();const clean=String(text).replace(/[ *_#]/g,""),u=new SpeechSynthesisUtterance(clean);u.lang="en-US";u.rate=.98;u.pitch=1;const chars=Array.from(clean);let pos=0;u.onstart=()=>{window.saeedAvatar?.play?.("talk");speechTimer=setInterval(()=>{if(pos>=chars.length){clearInterval(speechTimer);speechTimer=null;return}const ch=chars[pos++],v=phonemeMap[ch.toLowerCase()]||"aa";["aa","ee","oo","oh","fv","mbp"].forEach(x=>window.saeedAvatar?.setViseme?.(x,0));if(!/\s/.test(ch))window.saeedAvatar?.setViseme?.(v,.72)},Math.max(45,70/u.rate))};u.onend=()=>{stopSpeaking();window.saeedAvatar?.play?.("idle")};u.onerror=e=>{report("ERROR","TTS LOCAL ERROR",e?.error||"Local TTS failed");stopSpeaking();window.saeedAvatar?.play?.("idle")};window.speechSynthesis.speak(u)}
 class RealtimeMic{
  constructor(){this.stream=null;this.ctx=null;this.source=null;this.processor=null;this.monitorGain=null;this.active=false}
  async start(mode="always"){if(mode==="off"){this.stop();return}if(this.active)return;if(!navigator.mediaDevices?.getUserMedia)throw new Error("Microphone capture is unavailable.");report("INFO","MIC START","Starting 3D-window microphone service",{mode});this.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});this.ctx=new AudioContext();this.source=this.ctx.createMediaStreamSource(this.stream);this.processor=this.ctx.createScriptProcessor(4096,1,1);this.processor.onaudioprocess=e=>{if(!this.active)return;const input=e.inputBuffer.getChannelData(0);let sum=0;for(let i=0;i<input.length;i++)sum+=input[i]*input[i];const rms=Math.sqrt(sum/Math.max(1,input.length));report("INFO","MIC LEVEL","Microphone level "+Math.round(Math.min(1,rms*4)*100)+"%",{level:Math.min(1,rms*4)});const ratio=24000/this.ctx.sampleRate,n=Math.max(1,Math.floor(input.length*ratio)),pcm=new Int16Array(n);for(let i=0;i<n;i++){const x=input[Math.min(input.length-1,Math.floor(i/ratio))]||0;pcm[i]=Math.max(-1,Math.min(1,x))*32767}let binary="";const bytes=new Uint8Array(pcm.buffer);for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));window.saeed.sendRealtimeAudio(btoa(binary))};this.source.connect(this.processor);this.monitorGain=this.ctx.createGain();this.monitorGain.gain.value=0;this.processor.connect(this.monitorGain);this.monitorGain.connect(this.ctx.destination);this.active=true;report("INFO","MIC ACTIVE","3D-window microphone capture is active",{mode})}
  stop(){this.active=false;try{this.processor?.disconnect()}catch{}try{this.monitorGain?.disconnect()}catch{}try{this.source?.disconnect()}catch{}try{this.stream?.getTracks().forEach(t=>t.stop())}catch{}try{this.ctx?.close()}catch{}this.processor=null;this.monitorGain=null;this.source=null;this.stream=null;this.ctx=null;window.saeed.stopRealtime();report("INFO","MIC STOP","3D-window microphone capture stopped")}
 }
 mic=new RealtimeMic();
 window.saeed.onMicMode(async mode=>{const m=String(mode||"always");try{if(m==="off"){mic.stop();return}const cfg=await window.saeed.getSettings();if(cfg?.sttProvider!=="whisper")await mic.start(m)}catch(e){report("ERROR","MIC START FAILURE",e.message,{mode:m})}});
 window.saeed.onRealtimeState(async(state,message)=>{if(state==="connected"){report("INFO","STT ACTIVE","Realtime speech-to-text connected");const cfg=await window.saeed.getSettings();if(cfg?.micMode!=="off"&&cfg?.sttProvider!=="whisper")try{await mic.start(cfg.micMode||"always")}catch(e){report("ERROR","MIC START FAILURE",e.message)}}else if(state==="error"){report("ERROR","REALTIME API ERROR",String(message||state))}});
 window.saeed.onRealtimeAudio(b=>{try{if(!mic.playCtx)mic.playCtx=new AudioContext();const raw=atob(b),pcm=new Int16Array(raw.length/2);for(let i=0;i<pcm.length;i++)pcm[i]=raw.charCodeAt(i*2)|(raw.charCodeAt(i*2+1)<<8);const buffer=mic.playCtx.createBuffer(1,pcm.length,24000),ch=buffer.getChannelData(0);for(let i=0;i<pcm.length;i++)ch[i]=pcm[i]/32768;const src=mic.playCtx.createBufferSource();src.buffer=buffer;src.connect(mic.playCtx.destination);const now=mic.playCtx.currentTime;mic.nextPlayTime=Math.max(now,mic.nextPlayTime||0);src.start(mic.nextPlayTime);mic.nextPlayTime+=buffer.duration;window.saeedAvatar?.play?.("talk");src.onended=()=>{if(mic.playCtx.currentTime>=mic.nextPlayTime-.02)window.saeedAvatar?.play?.("idle")}}catch(e){report("ERROR","TTS AUDIO PLAYBACK",e.message)}});
 window.saeed.onRealtimeAssistantDelta(t=>{realtimeAssistant+=String(t||"");window.saeedAvatar?.play?.("talk")});
 window.saeed.onRealtimeAssistantFinal(t=>{if(t){realtimeAssistant="";speak(t)}});
 window.saeed.onRealtimeUserFinal(t=>{if(t){const clean=cleanText(t);if(clean)report("INFO","STT RECEIVE TEXT","Realtime speech received",{text:clean})}});
 window.saeed.onRealtimeError(e=>report("ERROR","REALTIME API ERROR",String(e)));
 window.saeed.onLocalSttState((state,message)=>{report(state==="error"?"ERROR":"INFO","LOCAL STT STATE",String(message||state));if(state==="error")window.saeedAvatar?.setState?.("alert")});
 window.saeed.onLocalSttResult(async e=>{const text=cleanText(e?.text);if(!text)return;report("INFO","LOCAL STT RECEIVE TEXT","Offline Whisper transcript received",{text});window.saeedAvatar?.setState?.("think");try{const answer=await window.saeed.chat(text);if(answer?.error){report("ERROR","LLM RESPONSE",answer.error);return}if(answer){speak(answer);window.saeedAvatar?.setState?.("talk")}}catch(err){report("ERROR","VOICE BRAIN",err.message)}});
 window.saeed.onEvent(e=>{if(e?.type==="thinking")window.saeedAvatar?.setState?.("think");if(e?.type==="answer"){window.saeedAvatar?.setState?.("talk");window.saeedAvatar?.nod?.()}});
 window.addEventListener("load",async()=>{try{const cfg=await window.saeed.getSettings();if(cfg?.micMode!=="off"&&cfg?.sttProvider!=="whisper"&&String(cfg?.brainMode||"auto")==="realtime")await mic.start(cfg.micMode||"always");if(cfg?.sttProvider==="whisper"&&cfg?.micMode!=="off")report("INFO","LOCAL STT","Offline Whisper is managed by the main process and is independent of Chat")}catch(e){report("ERROR","VOICE STARTUP",e.message)}});
})();