const APP_ALIASES={notepad:"notepad.exe",calculator:"calc.exe",calc:"calc.exe",paint:"mspaint.exe",explorer:"explorer.exe","file explorer":"explorer.exe","task manager":"taskmgr.exe","control panel":"control.exe",settings:"ms-settings:",cmd:"cmd.exe","command prompt":"cmd.exe",powershell:"powershell.exe",terminal:"wt.exe",edge:"msedge.exe",chrome:"chrome.exe",firefox:"firefox.exe"};
class LocalBrain{constructor(registry){this.registry=registry}async call(name,args,answer){const out=await this.registry.call(name,args);return out?.ok===false?("I could not complete that: "+out.error):answer(out)}async handle(text){const t=String(text||"").trim(),l=t.toLowerCase();if(!t)return null;
if(/(?:what(?:'s| is) the time|current time|what time is it|كم الساعة|الساعة كم|الوقت الآن)/i.test(l)){const n=new Date();return "The local time is "+n.toLocaleTimeString()+" on "+n.toLocaleDateString()+"."}
if(/(?:today'?s date|what date is it|what day is it|تاريخ اليوم|ما هو تاريخ اليوم)/i.test(l)){return "Today is "+new Date().toLocaleDateString(undefined,{weekday:"long",year:"numeric",month:"long",day:"numeric"})+"."}
if(/(?:open|launch|start|show|run|شغل|افتح|تشغيل)\s+(.+)/i.test(t)){const m=t.match(/(?:open|launch|start|show|run|شغل|افتح|تشغيل)\s+(.+)/i);let name=m?.[1]?.trim()||"";const key=name.toLowerCase().replace(/^(my|the)\s+/,"");if(APP_ALIASES[key])return this.call("open_application",{application:APP_ALIASES[key]},()=> "Opened "+name+".");if(/^(this pc|my computer|computer|file explorer|جهاز الكمبيوتر|الكمبيوتر)$/i.test(name))return this.call("open_application",{application:"explorer.exe"},()=> "Opened File Explorer.");return this.call("open_application",{application:name},()=> "Opened "+name+".")}
if(/(?:show|list|what(?:'s| is) in|browse)\s+(?:the\s+)?(?:files|folder|directory|مجلد|ملفات)/i.test(l)){const m=t.match(/(?:in|of|the)\s+(.+)$/i);const dir=m?.[1]?.trim()||process.env.USERPROFILE||".";return this.call("list_directory",{directory:dir},o=> "Found "+(o.files?.length||0)+" items in "+dir+".")}
if(/(?:computer info|system info|pc info|system information|معلومات الجهاز|مواصفات الجهاز)/i.test(l))return this.call("system_info",{},o=> "Windows system: "+o.arch+", "+o.cpu+" CPU threads, "+(o.totalMemory/1073741824).toFixed(1)+" GB RAM.");
if(/(?:diagnose|diagnostic|health check|slow computer|computer problem|تشخيص|فحص الجهاز|الجهاز بطيء)/i.test(l))return this.call("diagnose_computer",{},o=> "Computer check completed. CPU load: "+(o.diagnostics?.cpuLoad ?? "unknown")+"%.");
if(/(?:disk|storage|free space|drive space|مساحة القرص|مساحة التخزين)/i.test(l))return this.call("disk_info",{},o=> "I found "+(o.drives?.length||0)+" local drives.");
if(/(?:network|internet connection|ip address|wifi|الشبكة|الانترنت|عنوان ip)/i.test(l))return this.call("network_info",{},o=> "Network inspection found "+(o.adapters?.length||0)+" adapter entries.");
if(/(?:running processes|processes|what is running|البرامج التي تعمل|العمليات)/i.test(l))return this.call("process_list",{},o=> "There are "+(o.processes?.length||0)+" process entries.");
if(/(?:active window|current window|what window|النافذة الحالية)/i.test(l))return this.call("active_window",{},o=> "The active window is "+(o.window?.title||"unknown")+".");
if(/(?:list windows|open windows|windows open|النوافذ المفتوحة)/i.test(l))return this.call("list_windows",{},o=> "I found "+(Array.isArray(o.windows)?o.windows.length:0)+" visible windows.");
if(/(?:screenshot|screen shot|capture my screen|صورة للشاشة|لقطة شاشة)/i.test(l))return this.call("screenshot",{},()=> "I captured the current screen.");
if(/(?:remember|تذكر|احفظ)/i.test(l))return this.call("remember",{fact:t.replace(/^(remember|تذكر|احفظ)\s*/i,"")},()=> "I saved that to local memory.");
if(/(?:my tasks|list tasks|show tasks|مهامي|قائمة المهام)/i.test(l))return this.call("list_tasks",{},o=> "You have "+(o.tasks?.length||0)+" saved tasks.");
return null}}
module.exports={LocalBrain};