const $=id=>document.getElementById(id);let settings={};const tabs=[...document.querySelectorAll(".tabs button")];tabs.forEach(b=>b.onclick=()=>{tabs.forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.id==="tab-"+b.dataset.tab));});$("close").onclick=()=>window.close();const defaults={characterBehavior:{breathing:true,blinking:true,expressions:true,speechFace:true,idle:true,walking:true,dancing:true,greeting:true,events:true,random:true,frequency:"normal",eventCooldownSec:30}};const behaviorSettings=()=>({...defaults.characterBehavior,...(settings.characterBehavior||{})});const permissionDefaults={files:"allow",applications:"allow",system:"allow",network:"allow",screen:"allow",mouseKeyboard:"allow",microphone:"allow",tasksMemory:"allow",credentials:"allow",destructive:"allow"};const permissionSettings=()=>({...permissionDefaults,...(settings.permissions||{})});
function fill(){const s=settings||{},b=behaviorSettings();$("provider").value=s.provider||"openai";$("model").value=s.model||"gpt-5";$("baseUrl").value=s.baseUrl||"";$("sttProvider").value=s.sttProvider||"whisper";$("ttsProvider").value=s.ttsProvider||"local";$("maxSteps").value=s.maxSteps||32;$("behaviorBreathing").checked=!!b.breathing;$("behaviorBlinking").checked=!!b.blinking;$("behaviorExpressions").checked=!!b.expressions;$("behaviorSpeechFace").checked=!!b.speechFace;$("behaviorIdle").checked=!!b.idle;$("behaviorWalking").checked=!!b.walking;$("behaviorDancing").checked=!!b.dancing;$("behaviorGreeting").checked=!!b.greeting;$("behaviorEvents").checked=!!b.events;$("behaviorRandom").checked=!!b.random;$("behaviorFrequency").value=b.frequency;$("behaviorCooldown").value=b.eventCooldownSec;$("apiKey").placeholder=s.hasApiKey?"Saved securely — leave blank to keep it":"Enter API key";$("sttKey").placeholder=s.hasSttApiKey?"Saved securely — leave blank to keep it":"Enter STT API key";$("ttsKey").placeholder=s.hasTtsApiKey?"Saved securely — leave blank to keep it":"Enter TTS API key";$("realtimeKey").placeholder=s.hasRealtimeApiKey?"Saved securely — leave blank to keep it":"Enter Realtime API key"}
async function load(){settings=await window.saeed.getSettings()||{};fill();const p=permissionSettings();for(const id of Object.keys(permissionDefaults)){const el=$("permission-"+id);if(el)el.value=p[id]}await refreshHistory();await refreshSystem();refreshPermissionSummary()}async function save(p,button){try{settings=await window.saeed.setSettings({...settings,...p});fill();button.textContent="Saved";setTimeout(()=>button.textContent="Save",1200)}catch(e){alert(e.message)}}$("saveApi").onclick=()=>{const k=$("apiKey").value.trim();save({provider:$("provider").value,model:$("model").value,baseUrl:$("baseUrl").value,...(k?{apiKey:k}:{})},$("saveApi"))};$("saveVoice").onclick=()=>{const p={sttProvider:$("sttProvider").value,ttsProvider:$("ttsProvider").value};const a=$("sttKey").value.trim(),b=$("ttsKey").value.trim(),c=$("realtimeKey").value.trim();if(a)p.sttApiKey=a;if(b)p.ttsApiKey=b;if(c)p.realtimeApiKey=c;save(p,$("saveVoice"))};$("saveCharacter").onclick=()=>{const b={breathing:$("behaviorBreathing").checked,blinking:$("behaviorBlinking").checked,expressions:$("behaviorExpressions").checked,speechFace:$("behaviorSpeechFace").checked,idle:$("behaviorIdle").checked,walking:$("behaviorWalking").checked,dancing:$("behaviorDancing").checked,greeting:$("behaviorGreeting").checked,events:$("behaviorEvents").checked,random:$("behaviorRandom").checked,frequency:$("behaviorFrequency").value,eventCooldownSec:Math.max(5,Math.min(300,Number($("behaviorCooldown").value)||30))};save({characterBehavior:b},$("saveCharacter"))};function refreshPermissionSummary(){
 const vals=Object.keys(permissionDefaults).map(id=>$("permission-"+id)?.value).filter(Boolean);
 $("permissionAllowCount").textContent=vals.filter(v=>v==="allow").length;
 $("permissionAskCount").textContent=vals.filter(v=>v==="ask").length;
 $("permissionDenyCount").textContent=vals.filter(v=>v==="deny").length;
}
function setAllPermissions(value){for(const id of Object.keys(permissionDefaults)){const el=$("permission-"+id);if(el)el.value=value}refreshPermissionSummary()}
$("allowAllPermissions").onclick=()=>setAllPermissions("allow");
$("denyAllPermissions").onclick=()=>setAllPermissions("deny");
$("askAllPermissions").onclick=()=>setAllPermissions("ask");
for(const id of Object.keys(permissionDefaults))$("permission-"+id)?.addEventListener("change",refreshPermissionSummary);
$("savePermissions").onclick=()=>save({permissions:Object.fromEntries(Object.keys(permissionDefaults).map(id=>[id,$("permission-"+id).value]))},$("savePermissions"));$("saveAgent").onclick=()=>save({brainMode:"auto",maxSteps:Math.max(1,Math.min(100,Number($("maxSteps").value)||32))},$("saveAgent"));async function refreshHistory(){try{const h=await window.saeed.getHistory();$("historyCount").textContent=Array.isArray(h)?h.length:0}catch(e){$("historyCount").textContent="?"}}$("refreshHistory").onclick=refreshHistory;async function refreshSystem(){try{const x=await window.saeed.getCpuMetrics();$("systemInfo").textContent=x?.detail||"System metrics unavailable"}catch(e){$("systemInfo").textContent=e.message}}$("refreshSystem").onclick=refreshSystem;load();