const {contextBridge,ipcRenderer}=require("electron");
contextBridge.exposeInMainWorld("saeed",{
 chat:(text,image=null)=>ipcRenderer.invoke("chat",{text,image}),
 capture:()=>ipcRenderer.invoke("capture"),\n checkForUpdates:()=>ipcRenderer.invoke("update:check"),\n installUpdate:()=>ipcRenderer.invoke("update:install"),\n downloadUpdate:()=>ipcRenderer.invoke("update:download"),
 getHistory:()=>ipcRenderer.invoke("history:get"),
 getSettings:()=>ipcRenderer.invoke("settings:get"),
 setSettings:s=>ipcRenderer.invoke("settings:set",s),
 moveWindowBy:(dx,dy)=>ipcRenderer.send("window:move-by",dx,dy),
 showChat:()=>ipcRenderer.send("window:show-chat"),
 onEvent:f=>ipcRenderer.on("agent:event",(_,e)=>f(e)),
 onConfirmation:f=>ipcRenderer.on("agent:confirm",(_,e)=>f(e)),
 respondConfirmation:(id,approved)=>ipcRenderer.invoke("agent:confirm-response",id,approved),
 onScreenCapture:f=>ipcRenderer.on("screen:capture",(_,e)=>f(e)),
 onShowChat:f=>ipcRenderer.on("chat:show",()=>f()),
 onShowSettings:f=>ipcRenderer.on("settings:show",()=>f()),
 startRealtime:o=>ipcRenderer.invoke("realtime:start",o||{}),
 stopRealtime:()=>ipcRenderer.invoke("realtime:stop"),
 sendRealtimeAudio:b=>ipcRenderer.invoke("realtime:audio",b),
 sendRealtimeText:t=>ipcRenderer.invoke("realtime:text",t),
 cancelRealtime:()=>ipcRenderer.invoke("realtime:cancel"),
 onRealtimeState:f=>ipcRenderer.on("realtime:state",(_,state,message)=>f(state,message)),
 onRealtimeAudio:f=>ipcRenderer.on("realtime:audio",(_,b)=>f(b)),
 onRealtimeAssistantDelta:f=>ipcRenderer.on("realtime:assistant-delta",(_,t)=>f(t)),
 onRealtimeAssistantFinal:f=>ipcRenderer.on("realtime:assistant-final",(_,t)=>f(t)),
 onRealtimeUserDelta:f=>ipcRenderer.on("realtime:user-delta",(_,t)=>f(t)),
 onRealtimeUserFinal:f=>ipcRenderer.on("realtime:user-final",(_,t)=>f(t)),
 onRealtimeDone:f=>ipcRenderer.on("realtime:done",(_,s)=>f(s)),
 onRealtimeError:f=>ipcRenderer.on("realtime:error",(_,e)=>f(e)),\n onUpdateState:f=>ipcRenderer.on("update:state",(_,state,message)=>f(state,message)),\n onUpdateAvailable:f=>ipcRenderer.on("update:available",(_,info)=>f(info)),\n onUpdateProgress:f=>ipcRenderer.on("update:progress",(_,info)=>f(info)),\n onUpdateDownloaded:f=>ipcRenderer.on("update:downloaded",(_,info)=>f(info))
});