const {contextBridge,ipcRenderer}=require("electron");
const on=(channel,handler)=>ipcRenderer.on(channel,(_, ...args)=>handler(...args));
const send=(channel,...args)=>ipcRenderer.send(channel,...args);
const invoke=(channel,...args)=>ipcRenderer.invoke(channel,...args);
contextBridge.exposeInMainWorld("saeed",{
 isCiE2E:process.argv.includes("--ci-e2e"),
 system:{
  capture:()=>invoke("capture"),checkForUpdates:()=>invoke("update:check"),installUpdate:()=>invoke("update:install"),downloadUpdate:()=>invoke("update:download"),showUpdateStatus:()=>invoke("update:show-status"),closeUpdateToast:()=>invoke("update:toast-close"),getUpdateSnapshot:()=>invoke("update:snapshot"),
  getSettings:()=>invoke("settings:get"),getAppVersion:()=>invoke("app:version"),setSettings:s=>invoke("settings:set",s),clearAllApis:()=>invoke("api:clear-all"),storeEmailCredential:(provider,account,username,password)=>invoke("email:credential:store",provider,account,username,password),saveEmailAccount:record=>invoke("email:account:save",record),getEmailAccount:(provider,account)=>invoke("email:account:get",provider,account),testEmailConnection:record=>invoke("email:connection:test",record),reportDiagnostic:(level,stage,message,meta)=>invoke("diagnostic:report",level,stage,message,meta),getDiagnosticSnapshot:()=>invoke("diagnostic:snapshot"),testApiConnection:service=>invoke("api-status:test",service),testAllApiConnections:()=>invoke("api-status:test-all"),getCpuMetrics:()=>invoke("cpu:metrics"),getResourceSnapshot:()=>invoke("resource:snapshot"),onCpuMetrics:f=>on("cpu:metrics",f),
  showStatus:()=>invoke("status:show"),showPerformance:()=>invoke("performance:show"),showSettings:()=>invoke("settings:show"),showAddons:()=>invoke("addons:show"),showLearning:()=>invoke("learning:show"),getTranscriptLabelEnabled:()=>invoke("transcript-label:get"),setTranscriptLabelEnabled:enabled=>invoke("transcript-label:set",Boolean(enabled)),onTranscriptLabel:f=>on("character:transcript-label",f),onAddonsRefresh:f=>on("addons:refresh",f),onStatusSnapshot:f=>on("diagnostic:snapshot",f),onDiagnostic:f=>on("diagnostic:event",f),onDiagnosticState:f=>on("diagnostic:state",f),onScreenCapture:f=>on("screen:capture",f),onShowPerformance:f=>on("performance:show",f),
  onUpdateState:f=>on("update:state",f),onUpdateAvailable:f=>on("update:available",f),onUpdateProgress:f=>on("update:progress",f),onUpdateDownloaded:f=>on("update:downloaded",f),onUpdateToast:f=>on("update-toast",f),onUpdateCheckUi:f=>on("update:check-ui",f)
 },
 character:{
  chooseCharacter:()=>invoke("character:choose"),getPendingCharacter:()=>invoke("character:get-pending"),getCharacter3DSettings:()=>invoke("character:3d:get"),setCharacter3DSettings:patch=>invoke("character:3d:set",patch),getCharacterController:()=>invoke("character:controller:get"),characterController:command=>invoke("character:controller:command",command),characterLoadResult:(generation,result)=>send("character:load-result",Number(generation)||0,result||{}),
  onCharacter3DSettings:f=>on("character:3d-settings",f),onCharacterSelected:f=>on("character:selected",f),onCharacterCommand:f=>on("character:command",f),characterCommandResult:(id,result)=>send("character:command-result",id,result),onCharacterVisibility:f=>on("character:visibility",f),onCharacterBehavior:f=>on("character:behavior",f),characterActivity:()=>send("character:activity"),characterRendererReady:()=>send("character:renderer-ready"),moveWindowBy:(dx,dy)=>send("window:move-by",dx,dy),
  show3DStatus:()=>invoke("3d-status:show"),get3DStatus:()=>invoke("3d:query"),report3DStatus:(requestId,status)=>send("3d:status-report",requestId,status),on3DQuery:f=>on("3d:query",f),on3DStatus:f=>on("3d:status",f),showRestPoseEditor:()=>invoke("rest-pose:show"),closeWindow:()=>send("window:close-self")
 },
 voice:{
  voiceChat:text=>invoke("voice:chat",String(text||"")),reportMicLevel:level=>send("mic:level",Number(level)||0),onMicLevel:f=>on("mic:level",f),startRealtime:o=>invoke("realtime:start",o||{}),stopRealtime:()=>invoke("realtime:stop"),sendRealtimeAudio:b=>invoke("realtime:audio",b),cancelRealtime:()=>invoke("realtime:cancel"),
  ttsSpeak:text=>invoke("tts:speak",String(text||"")),speakText:text=>invoke("voice:speak",String(text||"")),sttTranscribe:base64=>invoke("stt:transcribe",String(base64||"")),transcribeLocalWav:b=>invoke("local-stt:transcribe",b),setMicMode:mode=>invoke("mic:mode",mode),setVoiceMuted:muted=>invoke("voice:mute",Boolean(muted)),
  onVoiceMute:f=>on("voice:mute",f),onVoiceTts:f=>on("voice:tts",f),onVoiceSpeak:f=>on("voice:speak",f),onVoiceStop:f=>on("voice:stop",f),onMicMode:f=>on("mic:mode",f),onLocalSttState:f=>on("local-stt:state",f),onRealtimeState:f=>on("realtime:state",f),onRealtimeAudio:f=>on("realtime:audio",f),onRealtimeAssistantDelta:f=>on("realtime:assistant-delta",f),onRealtimeAssistantFinal:f=>on("realtime:assistant-final",f),onRealtimeUserFinal:f=>on("realtime:user-final",f),onRealtimeError:f=>on("realtime:error",f)
 },
 chat:{
  chat:(text,image=null)=>invoke("chat",{text,image}),getHistory:()=>invoke("history:get"),clearHistory:()=>invoke("history:clear"),listChats:()=>invoke("chat:list"),getCurrentChat:()=>invoke("chat:current"),getGlobalMemory:()=>invoke("chat:memory"),newChat:()=>invoke("chat:new"),selectChat:id=>invoke("chat:select",id),deleteChat:id=>invoke("chat:delete",id),exportConversations:()=>invoke("chat:export-conversations"),importConversations:()=>invoke("chat:import-conversations"),onChatSwitched:f=>on("chat:switched",f),
  moveChatBy:(dx,dy)=>send("chat:move-by",dx,dy),showChat:()=>send("window:show-chat"),closeChat:()=>send("window:close-chat"),setChatMousePassthrough:ignore=>send("chat:mouse-passthrough",Boolean(ignore)),minimizeChat:()=>invoke("chat:minimize"),onEvent:f=>on("agent:event",f),onShowChat:f=>on("chat:show",f)
 },
 tools:{onConfirmation:f=>on("agent:confirm",f),respondConfirmation:(id,approved)=>invoke("agent:confirm-response",id,approved)},
 learning:{list:()=>invoke("learning:list"),get:id=>invoke("learning:get",id),save:skill=>invoke("learning:save",skill),remove:id=>invoke("learning:remove",id),enable:(id,enabled)=>invoke("learning:enable",id,Boolean(enabled)),run:id=>invoke("learning:run",id),export:id=>invoke("learning:export",id),import:data=>invoke("learning:import",data),recordStart:(name,phrases)=>invoke("learning:record-start",name,phrases),recordStop:()=>invoke("learning:record-stop")},
 addons:{catalog:()=>invoke("addons:catalog"),enable:(id,enabled)=>invoke("addons:enable",id,Boolean(enabled)),install:(id,onProgress)=>{const handler=(_,addonId,state)=>{if(String(addonId)===String(id))onProgress?.(state)};ipcRenderer.on("addons:progress",handler);return invoke("addons:install",id).finally(()=>ipcRenderer.removeListener("addons:progress",handler))},uninstall:id=>invoke("addons:uninstall",id)}
});