const $=id=>document.getElementById(id);
let state={};let settings={};let events=[];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const label={unknown:"UNKNOWN",ready:"READY",active:"ACTIVE",connected:"CONNECTED",error:"ERROR",disconnected:"DISCONNECTED",disabled:"DISABLED"};
function cls(v){if(v==="error")return"err";if(v==="connected"||v==="active"||v==="ready")return"ok";return"warn"}
function render(){
 const items=[["mic","Microphone"],["cpu","CPU"],["brainApi","Brain API"],["brainLocal","Brain Local"],["stt","STT"],["tts","TTS"],["glb","GLB / Character"]];
 $("cards").innerHTML=items.map(([k,n])=>{const v=state[k]||{};const level=k==="mic"?Math.max(0,Math.min(1,Number(v.level||0))):0;return `<div class="card"><div class="row"><i class="dot ${cls(v.state)}"></i><span class="name">${n}</span><span class="state">${esc(label[v.state]||String(v.state||"UNKNOWN").toUpperCase())}</span></div><div class="detail">${esc(v.detail||"No verified state yet")}</div>${k==="mic"?`<div class="meter"><i style="width:${Math.round(level*100)}%"></i></div><div class="levelText">Input level ${Math.round(level*100)}%</div>`:k==="cpu"?`<div class="meter"><i style="width:${Math.min(100,Math.max(0,Number(v.percent||0)))}%"></i></div><div class="levelText">CPU ${Number(v.percent||0).toFixed(1)}%</div>`:""}</div>`}).join("");
 $("modeValue").textContent=settings.brainMode||"auto";$("micValue").textContent=settings.micMode||"off";
}
function add(e){if(!e)return;events.unshift(e);events=events.slice(0,300);const d=document.createElement("div");d.className="event "+String(e.level||"").toLowerCase();d.innerHTML=`<span class="time">${esc(e.time||"")}</span><b>${esc(e.level||"")}</b> | ${esc(e.stage||"")} | ${esc(e.message||"")}`;$("stream").prepend(d);while($("stream").children.length>300)$("stream").lastChild.remove()}
async function refresh(){try{const x=await window.saeed.getDiagnosticSnapshot();state=x?.state||{};render();const s=await window.saeed.getSettings();settings=s||{};render()}catch(e){add({time:new Date().toISOString(),level:"ERROR",stage:"STATUS",message:e.message})}}
async function setMode(mode){try{await window.saeed.setSettings({...settings,brainMode:mode});settings=await window.saeed.getSettings();add({time:new Date().toISOString(),level:"INFO",stage:"CONTROL",message:"Brain mode requested: "+mode});render()}catch(e){add({time:new Date().toISOString(),level:"ERROR",stage:"CONTROL",message:e.message})}}
async function setMic(mode){try{await window.saeed.setSettings({...settings,micMode:mode,alwaysListening:mode==="always"});settings=await window.saeed.getSettings();add({time:new Date().toISOString(),level:"INFO",stage:"CONTROL",message:"Microphone mode requested: "+mode});render()}catch(e){add({time:new Date().toISOString(),level:"ERROR",stage:"CONTROL",message:e.message})}}
$("openLog").onclick=()=>window.saeed.openDiagnosticsLog();$("refresh").onclick=refresh;$("brainAuto").onclick=()=>setMode("auto");$("brainLocal").onclick=()=>setMode("local");$("brainApi").onclick=()=>setMode("api");$("brainRealtime").onclick=()=>setMode("realtime");$("micOn").onclick=()=>setMic("always");$("micOff").onclick=()=>setMic("off");$("realtimeStart").onclick=async()=>{try{await setMode("realtime");await window.saeed.startRealtime({});}catch(e){add({time:new Date().toISOString(),level:"ERROR",stage:"REALTIME CONTROL",message:e.message})}};$("realtimeStop").onclick=async()=>{try{await window.saeed.stopRealtime();await setMode(settings.brainMode==="realtime"?"local":settings.brainMode||"auto")}catch(e){add({time:new Date().toISOString(),level:"ERROR",stage:"REALTIME CONTROL",message:e.message})}};
window.saeed.onStatusSnapshot(x=>{state=x?.state||{};render()});window.saeed.onDiagnosticState(x=>{state=x||{};render()});window.saeed.onDiagnostic(add);window.saeed.onRealtimeState((s,m)=>{add({time:new Date().toISOString(),level:s==="error"?"ERROR":"INFO",stage:"REALTIME "+String(s).toUpperCase(),message:m||s});refresh()});window.saeed.onRealtimeError(e=>add({time:new Date().toISOString(),level:"ERROR",stage:"REALTIME API ERROR",message:String(e)}));
refresh();